// Code generated by scorix. DO NOT EDIT.
package types

type ClientConnectReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
}

type ClientDisconnectReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
}

type ClientGeneralReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
}

type ClientGeneralRes struct {
	Info      string   `json:"info"`
	TotalDb   int32    `json:"total_db"`
	Databases []DbInfo `json:"databases"`
}

type ClientGetSlowQueryReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
}

type ClientGetSlowQueryRes struct {
	Items []SlowQueryItem `json:"items"`
}

type ClientKeyCreateReq struct {
	ConnectionId  string      `json:"connection_id"`
	DatabaseIndex int32       `json:"database_index"`
	Key           string      `json:"key"`
	Kind          string      `json:"kind"`
	Ttl           int64       `json:"ttl"`
	ValueString   string      `json:"value_string"`
	ValueJson     string      `json:"value_json"`
	ValueList     []string    `json:"value_list"`
	ValueHash     []KeyValue  `json:"value_hash"`
	ValueSet      []string    `json:"value_set"`
	ValueZset     []ZMember   `json:"value_zset"`
	ValueStream   StreamValue `json:"value_stream"`
}

type ClientKeyDeleteReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
}

type ClientKeyNameUpdateReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	CurrentName   string `json:"current_name"`
	NewName       string `json:"new_name"`
}

type ClientKeyTtlUpdateReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	KeyName       string `json:"key_name"`
	KeyTtl        int64  `json:"key_ttl"`
}

type ClientKeyValueUpdateReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Kind          string `json:"kind"`
	Value         string `json:"value"`
}

type ClientKeysDeleteByPrefixReq struct {
	ConnectionId  string   `json:"connection_id"`
	DatabaseIndex int32    `json:"database_index"`
	Prefix        string   `json:"prefix"`
	Keys          []string `json:"keys"`
}

type ClientKeysDeleteByPrefixRes struct {
	TotalDeleted int32 `json:"total_deleted"`
}

type ClientKeysDeleteProgressEvent struct {
	ConnectionId string `json:"connection_id"`
	Prefix       string `json:"prefix"`
	Deleted      int64  `json:"deleted"`
	Total        int64  `json:"total"`
	Status       string `json:"status"`
}

type ClientKeysMetadataReq struct {
	ConnectionId  string   `json:"connection_id"`
	DatabaseIndex int32    `json:"database_index"`
	Keys          []string `json:"keys"`
}

type ClientKeysMetadataRes struct {
	Items []KeyMetadata `json:"items"`
}

type ClientKeysScanByPrefixRes struct {
	Keys       []string `json:"keys"`
	NextCursor string   `json:"next_cursor"`
}

type ClientLoadAllKeysReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Prefix        string `json:"prefix"`
	Count         int64  `json:"count"`
	Cursor        string `json:"cursor"`
}

type ClientLoadAllKeysRes struct {
	Keys   []string `json:"keys"`
	Cursor string   `json:"cursor"`
}

type ClientLoadKeyDetailReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
}

type ClientLoadKeyDetailRes struct {
	Key   string  `json:"key"`
	Value string  `json:"value"`
	Kind  string  `json:"kind"`
	Ttl   float64 `json:"ttl"`
	Total int64   `json:"total"`
}

type ClientLoadKeyValuePageReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Kind          string `json:"kind"`
	Cursor        string `json:"cursor"`
	PageSize      int64  `json:"page_size"`
}

type ClientLoadKeyValuePageRes struct {
	Items      []KeyValuePageItem `json:"items"`
	NextCursor string             `json:"next_cursor"`
	HasMore    bool               `json:"has_more"`
}

type ClientSearchKeysReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Prefix        string `json:"prefix"`
	Count         int64  `json:"count"`
	Cursor        string `json:"cursor"`
}

type ClientSearchKeysRes struct {
	Keys []string `json:"keys"`
}

type ClientSetReadOnlyReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	ReadOnly      bool   `json:"read_only"`
}

type ConnectionListRes struct {
	Items []ConnectionReq `json:"items"`
}

type ConnectionReq struct {
	Id               string   `json:"id"`
	Mode             string   `json:"mode"`
	Name             string   `json:"name"`
	Network          string   `json:"network"`
	Host             string   `json:"host"`
	Port             int32    `json:"port"`
	Addrs            string   `json:"addrs"`
	SentinelMaster   string   `json:"sentinel_master"`
	SentinelUsername string   `json:"sentinel_username"`
	SentinelPassword string   `json:"sentinel_password"`
	Sock             string   `json:"sock"`
	Username         string   `json:"username"`
	Password         string   `json:"password"`
	AddrMapping      string   `json:"addr_mapping"`
	ExecTimeout      int64    `json:"exec_timeout"`
	DialTimeout      int64    `json:"dial_timeout"`
	KeySize          int64    `json:"key_size"`
	SshEnable        bool     `json:"ssh_enable"`
	SshId            string   `json:"ssh_id"`
	ProxyEnable      bool     `json:"proxy_enable"`
	ProxyId          string   `json:"proxy_id"`
	TlsEnable        bool     `json:"tls_enable"`
	TlsId            string   `json:"tls_id"`
	Ssh              SshReq   `json:"ssh"`
	Proxy            ProxyReq `json:"proxy"`
	Tls              TlsReq   `json:"tls"`
	GroupId          string   `json:"group_id"`
	LastDb           int32    `json:"last_db"`
	ReadOnly         bool     `json:"read_only"`
}

type ConsoleInputEvent struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Id            string `json:"id"`
	Command       string `json:"command"`
}

type ConsoleOutputEvent struct {
	ConnectionId string `json:"connection_id"`
	Id           string `json:"id"`
	Stdout       string `json:"stdout"`
	Stderr       string `json:"stderr"`
}

type DbInfo struct {
	Index   int32  `json:"index"`
	Name    string `json:"name"`
	Keys    int32  `json:"keys"`
	Expires int32  `json:"expires"`
	AvgTtl  int64  `json:"avg_ttl"`
}

type Empty struct {
}

type GroupItem struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type GroupListRes struct {
	Items []GroupItem `json:"items"`
}

type GroupUpsertReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type IdReq struct {
	Id string `json:"id"`
}

type KeyHashFieldDelReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Field         string `json:"field"`
}

type KeyListItemDelReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Index         int64  `json:"index"`
	Value         string `json:"value"`
}

type KeyLoadReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Cursor        string `json:"cursor"`
	Count         int64  `json:"count"`
}

type KeyLoadRes struct {
	Keys   []string `json:"keys"`
	Cursor string   `json:"cursor"`
}

type KeyMetadata struct {
	Key  string `json:"key"`
	Type string `json:"type"`
	Ttl  int64  `json:"ttl"`
	Size int64  `json:"size"`
}

type KeySetMemberDelReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Member        string `json:"member"`
}

type KeyStreamEntryDelReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	EntryId       string `json:"entry_id"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValuePageItem struct {
	Field  string  `json:"field"`
	Value  string  `json:"value"`
	Index  int64   `json:"index"`
	Member string  `json:"member"`
	Score  float64 `json:"score"`
	Id     string  `json:"id"`
}

type KeyZSetMemberDelReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Key           string `json:"key"`
	Member        string `json:"member"`
}

type MonitorFrame struct {
	Kind         string `json:"kind"`
	ConnectionId string `json:"connection_id"`
	Active       bool   `json:"active"`
	Line         string `json:"line"`
}

type MonitorMessageEvent struct {
	ConnectionId string `json:"connection_id"`
	Line         string `json:"line"`
}

type MonitorReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
}

type MonitorStatusEvent struct {
	ConnectionId string `json:"connection_id"`
	Active       bool   `json:"active"`
}

type MonitorStatusRes struct {
	Active bool `json:"active"`
}

type ProxyListRes struct {
	Items []ProxyReq `json:"items"`
}

type ProxyReq struct {
	Id       string `json:"id"`
	Protocol string `json:"protocol"`
	Host     string `json:"host"`
	Port     int32  `json:"port"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type PubSubPublishReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
	Channel       string `json:"channel"`
	Message       string `json:"message"`
}

type PubSubStreamReq struct {
	ConnectionId  string `json:"connection_id"`
	DatabaseIndex int32  `json:"database_index"`
}

type PubSubSubscribeReq struct {
	ConnectionId  string   `json:"connection_id"`
	DatabaseIndex int32    `json:"database_index"`
	Channels      []string `json:"channels"`
}

type PubsubMessageEvent struct {
	ConnectionId string `json:"connection_id"`
	Channel      string `json:"channel"`
	Message      string `json:"message"`
	Pattern      string `json:"pattern"`
}

type SettingGetReq struct {
	Key string `json:"key"`
}

type SettingGetRes struct {
	Value string `json:"value"`
}

type SettingItem struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SettingListRes struct {
	Items []SettingItem `json:"items"`
}

type SettingSetReq struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SlowQueryItem struct {
	Id         int64    `json:"id"`
	Timestamp  int64    `json:"timestamp"`
	Duration   int64    `json:"duration"`
	Command    []string `json:"command"`
	ClientAddr string   `json:"client_addr"`
	ClientName string   `json:"client_name"`
}

type SshListRes struct {
	Items []SshReq `json:"items"`
}

type SshReq struct {
	Id         string `json:"id"`
	Host       string `json:"host"`
	Port       int32  `json:"port"`
	Username   string `json:"username"`
	Kind       string `json:"kind"`
	Password   string `json:"password"`
	PrivateKey string `json:"private_key"`
	Passphrase string `json:"passphrase"`
	Timeout    int64  `json:"timeout"`
}

type StreamValue struct {
	Id     string `json:"id"`
	Values string `json:"values"`
}

type SystemInfoRes struct {
	Version string `json:"version"`
	Os      string `json:"os"`
	Arch    string `json:"arch"`
	Runtime string `json:"runtime"`
}

type TlsListRes struct {
	Items []TlsReq `json:"items"`
}

type TlsReq struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	UseSni     bool   `json:"use_sni"`
	ServerName string `json:"server_name"`
	Verify     bool   `json:"verify"`
	ClientAuth bool   `json:"client_auth"`
	CaCert     string `json:"ca_cert"`
	Cert       string `json:"cert"`
	Key        string `json:"key"`
}

type UpsertRes struct {
	Id string `json:"id"`
}

type ZMember struct {
	Member string  `json:"member"`
	Score  float64 `json:"score"`
}
