// Code generated by scorix.
package ssh

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.SshListRes, error) {
	sshs, err := l.svcCtx.SshModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	var items []types.SshReq
	for _, s := range sshs {
		items = append(items, types.SshReq{
			Id:         s.ID,
			Host:       s.Host,
			Port:       int32(s.Port),
			Username:   s.Username,
			Kind:       s.Kind,
			Password:   "",
			PrivateKey: "",
			Passphrase: "",
			Timeout:    s.Timeout,
		})
	}

	return &types.SshListRes{
		Items: items,
	}, nil
}
