// Code generated by scorix.
package ssh

import (
	"context"
	"fmt"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"golang.org/x/crypto/ssh"
)

type TestLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewTestLogic(ctx context.Context, svcCtx *svc.ServiceContext) *TestLogic {
	return &TestLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *TestLogic) Test(params *types.SshReq) (*types.Empty, error) {
	s := model.Ssh{
		Host:       params.Host,
		Port:       int64(params.Port),
		Username:   params.Username,
		Kind:       params.Kind,
		Password:   params.Password,
		PrivateKey: params.PrivateKey,
		Passphrase: params.Passphrase,
		Timeout:    params.Timeout,
	}

	if params.Id != "" && (s.Password == "" || s.PrivateKey == "" || s.Passphrase == "") {
		if stored, err := l.svcCtx.SshModel.FindOne(l.ctx, params.Id); err == nil {
			if s.Password == "" {
				s.Password = stored.Password
			}
			if s.PrivateKey == "" {
				s.PrivateKey = stored.PrivateKey
			}
			if s.Passphrase == "" {
				s.Passphrase = stored.Passphrase
			}
		}
	}

	config, err := s.BuildClientCfg()
	if err != nil {
		return nil, err
	}

	addr := s.Addr()
	conn, err := ssh.Dial("tcp", addr, config)
	if err != nil {
		return nil, fmt.Errorf("ssh connect failed: %w", err)
	}
	defer conn.Close()

	return &types.Empty{}, nil
}
