// Code generated by scorix.
package ssh

import (
	"context"
	"database/sql"
	"errors"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type UpsertLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpsertLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpsertLogic {
	return &UpsertLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UpsertLogic) Upsert(params *types.SshReq) (*types.UpsertRes, error) {
	var s *model.Ssh
	if params.Id != "" {
		existing, err := l.svcCtx.SshModel.FindOne(l.ctx, params.Id)
		if err == nil {
			s = existing
		} else if !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
	}

	isNew := s == nil
	if isNew {
		s = &model.Ssh{
			ID: params.Id,
		}
	}

	s.Host = params.Host
	s.Port = int64(params.Port)
	s.Username = params.Username
	s.Kind = params.Kind
	s.Timeout = params.Timeout

	if isNew || params.Password != "" {
		s.Password = params.Password
	}
	if isNew || params.PrivateKey != "" {
		s.PrivateKey = params.PrivateKey
	}
	if isNew || params.Passphrase != "" {
		s.Passphrase = params.Passphrase
	}

	if isNew {
		if _, err := l.svcCtx.SshModel.Insert(l.ctx, s); err != nil {
			return nil, err
		}
	} else {
		if err := l.svcCtx.SshModel.Update(l.ctx, s); err != nil {
			return nil, err
		}
	}

	return &types.UpsertRes{Id: s.ID}, nil
}
