// Code generated by scorix.
package system

import (
	"context"
	"runtime"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type InfoLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewInfoLogic(ctx context.Context, svcCtx *svc.ServiceContext) *InfoLogic {
	return &InfoLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *InfoLogic) Info(params *types.Empty) (*types.SystemInfoRes, error) {
	return &types.SystemInfoRes{
		Version: "1.11.0",
		Os:      runtime.GOOS,
		Arch:    runtime.GOARCH,
		Runtime: runtime.Version(),
	}, nil
}
