// Code generated by scorix.
package console

import (
	"context"
	"errors"

	"github.com/redis/go-redis/v9"
	"github.com/samber/lo"
	"github.com/tradalab/scorix/app"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ExecLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewExecLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ExecLogic {
	return &ExecLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ExecLogic) Exec(req *types.ConsoleInputEvent, out app.Sink[types.ConsoleOutputEvent]) error {
	cli, err := l.svcCtx.RedisManager.Get(req.ConnectionId, int(req.DatabaseIndex))
	if err != nil {
		return out.Send(&types.ConsoleOutputEvent{ConnectionId: req.ConnectionId, Stderr: err.Error()})
	}

	cmds := SplitCmd(req.Command)
	if len(cmds) == 0 || cmds[0] == "" {
		return nil
	}

	args := lo.ToAnySlice(cmds)
	result, err := cli.Rdb.Do(l.ctx, args...).Result()
	if err != nil && !errors.Is(err, redis.Nil) {
		return out.Send(&types.ConsoleOutputEvent{ConnectionId: req.ConnectionId, Stderr: err.Error()})
	}

	return out.Send(&types.ConsoleOutputEvent{ConnectionId: req.ConnectionId, Stdout: AnyToString(result)})
}
