// Code generated by scorix.
package graph

import (
	"context"
	"encoding/json"
	"errors"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/graphreply"
)

type QueryLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewQueryLogic(ctx context.Context, svcCtx *svc.ServiceContext) *QueryLogic {
	return &QueryLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *QueryLogic) Query(params *types.GraphQueryReq) (*types.GraphQueryRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	query := strings.TrimSpace(params.Query)
	if query == "" {
		return nil, errors.New("query is empty")
	}

	cmd := readCmd(cli)
	reply, err := cli.Rdb.Do(l.ctx, cmd, params.Graph, query).Result()
	if err != nil {
		return nil, cli.ClassifyGraphErr(l.ctx, err, cmd)
	}

	res, err := graphreply.Parse(reply)
	if err != nil {
		return nil, err
	}

	return toRes(res), nil
}

// GRAPH.QUERY is flagged as a write whatever the Cypher inside says, so
// read-only mode blocks it outright. The RO twin keeps browsing alive there and
// leaves refusing a mutating query to the server, where read-only is enforced.
func readCmd(cli *svc.Client) string {
	if cli.ReadOnly.Load() {
		return "GRAPH.RO_QUERY"
	}
	return "GRAPH.QUERY"
}

func toRes(res *graphreply.Result) *types.GraphQueryRes {
	out := &types.GraphQueryRes{
		Columns: res.Columns,
		Rows:    make([]types.GraphRow, 0, len(res.Rows)),
		Nodes:   make([]types.GraphNode, 0, len(res.Nodes)),
		Edges:   make([]types.GraphEdge, 0, len(res.Edges)),
		Stats:   res.Stats,
	}

	for _, row := range res.Rows {
		out.Rows = append(out.Rows, types.GraphRow{Cells: row})
	}
	for _, n := range res.Nodes {
		out.Nodes = append(out.Nodes, types.GraphNode{
			Id:         n.ID,
			Labels:     n.Labels,
			Properties: encodeProps(n.Properties),
		})
	}
	for _, e := range res.Edges {
		out.Edges = append(out.Edges, types.GraphEdge{
			Id:         e.ID,
			Type:       e.Type,
			Src:        e.Src,
			Dst:        e.Dst,
			Properties: encodeProps(e.Properties),
		})
	}

	return out
}

func encodeProps(props map[string]any) string {
	if len(props) == 0 {
		return "{}"
	}
	b, err := json.Marshal(props)
	if err != nil {
		return "{}"
	}
	return string(b)
}
