// Code generated by scorix.
package graph

import (
	"context"
	"encoding/json"
	"strconv"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/graphreply"
)

type SchemaLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSchemaLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SchemaLogic {
	return &SchemaLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *SchemaLogic) Schema(params *types.GraphSchemaReq) (*types.GraphSchemaRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	res := &types.GraphSchemaRes{}

	// Labels probes strictly and the counts stay strict; the two lists between
	// them do not. A count that fails must not render as a confident "0 nodes".
	if res.Labels, err = l.column(cli, params.Graph, "CALL db.labels()"); err != nil {
		return nil, err
	}

	res.Relationships, _ = l.column(cli, params.Graph, "CALL db.relationshipTypes()")
	res.Properties, _ = l.column(cli, params.Graph, "CALL db.propertyKeys()")

	if res.Nodes, err = l.count(cli, params.Graph, "MATCH (n) RETURN count(n)"); err != nil {
		return nil, err
	}
	if res.Edges, err = l.count(cli, params.Graph, "MATCH ()-[r]->() RETURN count(r)"); err != nil {
		return nil, err
	}

	return res, nil
}

// Schema reads never mutate, but the entry point still follows the connection:
// hardcoding the RO twin would break every server too old to have the command.
func (l *SchemaLogic) query(cli *svc.Client, graph, cypher string) (*graphreply.Result, error) {
	cmd := readCmd(cli)
	reply, err := cli.Rdb.Do(l.ctx, cmd, graph, cypher).Result()
	if err != nil {
		return nil, cli.ClassifyGraphErr(l.ctx, err, cmd)
	}
	return graphreply.Parse(reply)
}

// Cells arrive JSON-encoded, so "Person" has to be unquoted to label a chip.
func (l *SchemaLogic) column(cli *svc.Client, graph, cypher string) ([]string, error) {
	res, err := l.query(cli, graph, cypher)
	if err != nil {
		return nil, err
	}

	out := make([]string, 0, len(res.Rows))
	for _, row := range res.Rows {
		if len(row) == 0 {
			continue
		}
		var s string
		if err := json.Unmarshal([]byte(row[0]), &s); err != nil {
			s = row[0]
		}
		out = append(out, s)
	}
	return out, nil
}

func (l *SchemaLogic) count(cli *svc.Client, graph, cypher string) (int64, error) {
	res, err := l.query(cli, graph, cypher)
	if err != nil {
		return 0, err
	}
	if len(res.Rows) == 0 || len(res.Rows[0]) == 0 {
		return 0, nil
	}
	return parseCount(res.Rows[0][0])
}

// Which JSON a count lands in depends on the build: most answer with a number,
// some render scalars as bulk strings, so "12" and 12 both have to parse.
// Anything else errors, because a zero is indistinguishable from an empty graph.
func parseCount(cell string) (int64, error) {
	var n json.Number
	if err := json.Unmarshal([]byte(cell), &n); err == nil {
		return n.Int64()
	}

	var s string
	if err := json.Unmarshal([]byte(cell), &s); err == nil {
		return strconv.ParseInt(strings.TrimSpace(s), 10, 64)
	}

	return strconv.ParseInt(strings.TrimSpace(cell), 10, 64)
}
