// Code generated by scorix. DO NOT EDIT.

// Package events is the typed event layer generated from @event annotations in
// the proto: topic constants, Go->JS emit helpers and JS->Go subscribers.
// Topics are part of the IPC contract - never emit or subscribe raw strings.
package events

import (
	"context"
	"encoding/json"

	"github.com/tradalab/scorix/app"

	"github.com/tradalab/rdms/internal/types"
)

// Emitter is the Go->JS event sink. *app.App satisfies it directly; service
// contexts satisfy it by delegating to app.Emit / app.EmitTo.
type Emitter interface {
	Emit(name string, data any)
	EmitTo(client app.ClientID, name string, data any) bool
}

// Registrar registers a JS->Go event handler - pass app.Event or svcCtx.On.
type Registrar func(name string, fn func(context.Context, json.RawMessage))

const (
	// EventClientState - server push (Go -> JS).
	EventClientState = "client:state"
)

// EmitClientState broadcasts to every connected frontend.
func EmitClientState(e Emitter, p *types.ClientStateEvent) {
	e.Emit(EventClientState, p)
}

// EmitClientStateTo targets one frontend; reports whether it is still connected.
func EmitClientStateTo(e Emitter, client app.ClientID, p *types.ClientStateEvent) bool {
	return e.EmitTo(client, EventClientState, p)
}

// EmitClientStateCtx targets the frontend bound to ctx - the client that
// invoked the current command/event. With no bound client (Go->Go invoke,
// tests) it broadcasts. Returns false when the bound client has disconnected,
// so long-running pumps can stop producing for a dead consumer.
func EmitClientStateCtx(ctx context.Context, e Emitter, p *types.ClientStateEvent) bool {
	if client, ok := app.ClientFrom(ctx); ok {
		return EmitClientStateTo(e, client, p)
	}
	EmitClientState(e, p)
	return true
}
