// Code generated by scorix.
package preset

import (
	"context"
	"encoding/json"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.SearchPresetListRes, error) {
	rows, err := l.svcCtx.SearchPresetModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	items := make([]types.SearchPresetItem, 0, len(rows))
	for _, r := range rows {
		var filters []types.KeyFilter
		if r.Filters != "" {
			_ = json.Unmarshal([]byte(r.Filters), &filters)
		}

		items = append(items, types.SearchPresetItem{
			Id:        r.ID,
			Name:      r.Name,
			Filters:   filters,
			MatchAll:  r.MatchAll != 0,
			KeyType:   r.KeyType,
			CreatedAt: r.CreatedAt.Unix(),
			UpdatedAt: r.UpdatedAt.Unix(),
		})
	}

	return &types.SearchPresetListRes{Items: items}, nil
}
