// Code generated by scorix.
package preset

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/keyfilter"
)

type UpsertLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpsertLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpsertLogic {
	return &UpsertLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UpsertLogic) Upsert(params *types.SearchPresetUpsertReq) (*types.UpsertRes, error) {
	name := strings.TrimSpace(params.Name)
	if name == "" {
		return nil, fmt.Errorf("name is required")
	}

	clauses := make([]keyfilter.Clause, 0, len(params.Filters))
	for _, f := range params.Filters {
		clauses = append(clauses, keyfilter.Clause{
			Pattern:    f.Pattern,
			Mode:       f.Mode,
			Exclude:    f.Exclude,
			IgnoreCase: f.IgnoreCase,
		})
	}
	if _, err := keyfilter.Compile(clauses, params.MatchAll); err != nil {
		return nil, err
	}

	blob, err := json.Marshal(params.Filters)
	if err != nil {
		return nil, err
	}

	matchAll := int64(0)
	if params.MatchAll {
		matchAll = 1
	}

	if params.Id != "" {
		p, err := l.svcCtx.SearchPresetModel.FindOne(l.ctx, params.Id)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
		if err == nil && p != nil {
			p.Name = name
			p.Filters = string(blob)
			p.MatchAll = matchAll
			p.KeyType = params.KeyType
			if err := l.svcCtx.SearchPresetModel.Update(l.ctx, p); err != nil {
				return nil, err
			}
			return &types.UpsertRes{Id: p.ID}, nil
		}
	}

	p := &model.SearchPreset{
		ID:       params.Id,
		Name:     name,
		Filters:  string(blob),
		MatchAll: matchAll,
		KeyType:  params.KeyType,
	}
	if _, err := l.svcCtx.SearchPresetModel.Insert(l.ctx, p); err != nil {
		return nil, err
	}

	return &types.UpsertRes{Id: p.ID}, nil
}
