// Code generated by scorix.
package monitor

import (
	"context"
	"fmt"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type StartLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewStartLogic(ctx context.Context, svcCtx *svc.ServiceContext) *StartLogic {
	return &StartLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *StartLogic) Start(params *types.MonitorReq) (*types.Empty, error) {
	c, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	c.MonitorMu.Lock()
	if c.MonitorActive {
		c.MonitorMu.Unlock()
		return &types.Empty{}, nil
	}

	ctx, cancel := context.WithCancel(context.Background())
	c.MonitorActive = true
	c.MonitorCancel = cancel
	c.MonitorMu.Unlock()

	ch := make(chan string, 1000)
	var m *redis.MonitorCmd
	var conn *redis.Conn

	rollback := func() {
		c.MonitorMu.Lock()
		c.MonitorActive = false
		c.MonitorCancel = nil
		c.MonitorMu.Unlock()
		cancel()
	}

	switch rdb := c.Rdb.(type) {
	case *redis.Client:
		conn = rdb.Conn()
		m = conn.Monitor(ctx, ch)
		m.Start()

		c.MonitorMu.Lock()
		c.Monitor = m
		c.MonitorConn = conn
		c.MonitorMu.Unlock()
	default:
		rollback()
		return nil, fmt.Errorf("MONITOR is only supported on standalone redis client")
	}

	eventOut := fmt.Sprintf("monitor:message:%s", params.ConnectionId)
	statusEvent := fmt.Sprintf("monitor:status:%s", params.ConnectionId)

	l.svcCtx.App.Evt().Emit(context.Background(), "", statusEvent, true)

	go func(m *redis.MonitorCmd, conn *redis.Conn, cancel context.CancelFunc) {
		defer func() {
			c.MonitorMu.Lock()
			if c.Monitor == m {
				c.Monitor = nil
				c.MonitorActive = false
			}
			if c.MonitorConn == conn {
				c.MonitorConn = nil
			}
			c.MonitorMu.Unlock()

			m.Stop()
			conn.Close()
			cancel()

			l.svcCtx.App.Evt().Emit(context.Background(), "", statusEvent, false)
		}()

		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-ch:
				if !ok {
					return
				}
				l.svcCtx.App.Evt().Emit(context.Background(), "", eventOut, msg)
			}
		}
	}(m, conn, cancel)

	return &types.Empty{}, nil
}
