// Code generated by scorix.
package monitor

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type StatusLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewStatusLogic(ctx context.Context, svcCtx *svc.ServiceContext) *StatusLogic {
	return &StatusLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *StatusLogic) Status(params *types.MonitorReq) (*types.MonitorStatusRes, error) {
	c, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	c.MonitorMu.Lock()
	active := c.MonitorActive
	c.MonitorMu.Unlock()

	return &types.MonitorStatusRes{
		Active: active,
	}, nil
}
