port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes

protected-mode no
bind 0.0.0.0
requirepass rdh_cluster_pwd
masterauth rdh_cluster_pwd
# cluster-announce-ip <HOST_IP>
# cluster-announce-port 7001
# cluster-announce-bus-port 17001
