port 26379

sentinel resolve-hostnames yes
sentinel announce-hostnames no

sentinel monitor mymaster redis-master 6379 1
sentinel auth-pass mymaster rdh_sentinel_master_pwd

sentinel announce-ip 127.0.0.1
sentinel announce-port 9001

sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1

requirepass rdh_sentinel_pwd
