/**
 * Code generated by scorix. DO NOT EDIT.
 */
import scorix from "@/lib/scorix";
import type * as T from "@/types";

export const client = {
  connect: (params: T.ClientConnectReq) => scorix.invoke<T.Empty>("client:connect", params),
  consoleConnect: (params: T.ClientConnectReq) => scorix.invoke<T.Empty>("client:console-connect", params),
  disconnect: (params: T.ClientDisconnectReq) => scorix.invoke<T.Empty>("client:disconnect", params),
  general: (params: T.ClientGeneralReq) => scorix.invoke<T.ClientGeneralRes>("client:general", params),
  getSlowQuery: (params: T.ClientGetSlowQueryReq) => scorix.invoke<T.ClientGetSlowQueryRes>("client:get-slow-query", params),
  loadAllKeys: (params: T.ClientLoadAllKeysReq) => scorix.invoke<T.ClientLoadAllKeysRes>("client:load-all-keys", params),
  loadKeyDetail: (params: T.ClientLoadKeyDetailReq) => scorix.invoke<T.ClientLoadKeyDetailRes>("client:load-key-detail", params),
  loadKeyValuePage: (params: T.ClientLoadKeyValuePageReq) => scorix.invoke<T.ClientLoadKeyValuePageRes>("client:load-key-value-page", params),
  keyCreate: (params: T.ClientKeyCreateReq) => scorix.invoke<T.Empty>("client:key-create", params),
  keyDelete: (params: T.ClientKeyDeleteReq) => scorix.invoke<T.Empty>("client:key-delete", params),
  keyNameUpdate: (params: T.ClientKeyNameUpdateReq) => scorix.invoke<T.Empty>("client:key-name-update", params),
  keyTtlUpdate: (params: T.ClientKeyTtlUpdateReq) => scorix.invoke<T.Empty>("client:key-ttl-update", params),
  keyValueUpdate: (params: T.ClientKeyValueUpdateReq) => scorix.invoke<T.Empty>("client:key-value-update", params),
  keysMetadata: (params: T.ClientKeysMetadataReq) => scorix.invoke<T.ClientKeysMetadataRes>("client:keys-metadata", params),
  keysDeleteByPrefix: (params: T.ClientKeysDeleteByPrefixReq) => scorix.serverStream<T.ClientKeysDeleteProgressEvent>("client:keys-delete-by-prefix", params),
  keysScanByPrefix: (params: T.ClientKeysDeleteByPrefixReq) => scorix.invoke<T.ClientKeysScanByPrefixRes>("client:keys-scan-by-prefix", params),
  searchKeys: (params: T.ClientSearchKeysReq) => scorix.invoke<T.ClientSearchKeysRes>("client:search-keys", params),
};

export const conn = {
  test: (params: T.ConnectionReq) => scorix.invoke<T.Empty>("conn:test", params),
};

export const key = {
  hashFieldDel: (params: T.KeyHashFieldDelReq) => scorix.invoke<T.Empty>("key:hash-field-del", params),
  listItemDel: (params: T.KeyListItemDelReq) => scorix.invoke<T.Empty>("key:list-item-del", params),
  load: (params: T.KeyLoadReq) => scorix.invoke<T.KeyLoadRes>("key:load", params),
  setMemberDel: (params: T.KeySetMemberDelReq) => scorix.invoke<T.Empty>("key:set-member-del", params),
  streamEntryDel: (params: T.KeyStreamEntryDelReq) => scorix.invoke<T.Empty>("key:stream-entry-del", params),
  zSetMemberDel: (params: T.KeyZSetMemberDelReq) => scorix.invoke<T.Empty>("key:z-set-member-del", params),
};

export const monitor = {
  start: (params: T.MonitorReq) => scorix.serverStream<T.MonitorFrame>("monitor:start", params),
  stop: (params: T.MonitorReq) => scorix.invoke<T.Empty>("monitor:stop", params),
  status: (params: T.MonitorReq) => scorix.invoke<T.MonitorStatusRes>("monitor:status", params),
};

export const pubsub = {
  stream: (params: T.PubSubStreamReq) => scorix.serverStream<T.PubsubMessageEvent>("pubsub:stream", params),
  subscribe: (params: T.PubSubSubscribeReq) => scorix.invoke<T.Empty>("pubsub:subscribe", params),
  unsubscribe: (params: T.PubSubSubscribeReq) => scorix.invoke<T.Empty>("pubsub:unsubscribe", params),
  publish: (params: T.PubSubPublishReq) => scorix.invoke<T.Empty>("pubsub:publish", params),
};

export const console = {
  exec: (params: T.ConsoleInputEvent) => scorix.serverStream<T.ConsoleOutputEvent>("console:exec", params),
};

export const proxy = {
  list: (params: T.Empty) => scorix.invoke<T.ProxyListRes>("proxy:list", params),
  upsert: (params: T.ProxyReq) => scorix.invoke<T.UpsertRes>("proxy:upsert", params),
  delete: (params: T.IdReq) => scorix.invoke<T.Empty>("proxy:delete", params),
};

export const ssh = {
  list: (params: T.Empty) => scorix.invoke<T.SshListRes>("ssh:list", params),
  test: (params: T.SshReq) => scorix.invoke<T.Empty>("ssh:test", params),
  upsert: (params: T.SshReq) => scorix.invoke<T.UpsertRes>("ssh:upsert", params),
  delete: (params: T.IdReq) => scorix.invoke<T.Empty>("ssh:delete", params),
};

export const tls = {
  list: (params: T.Empty) => scorix.invoke<T.TlsListRes>("tls:list", params),
  upsert: (params: T.TlsReq) => scorix.invoke<T.UpsertRes>("tls:upsert", params),
  delete: (params: T.IdReq) => scorix.invoke<T.Empty>("tls:delete", params),
};

export const connection = {
  list: (params: T.Empty) => scorix.invoke<T.ConnectionListRes>("connection:list", params),
  upsert: (params: T.ConnectionReq) => scorix.invoke<T.UpsertRes>("connection:upsert", params),
  delete: (params: T.IdReq) => scorix.invoke<T.Empty>("connection:delete", params),
};

export const system = {
  info: (params: T.Empty) => scorix.invoke<T.SystemInfoRes>("system:info", params),
};

export const group = {
  list: (params: T.Empty) => scorix.invoke<T.GroupListRes>("group:list", params),
  upsert: (params: T.GroupUpsertReq) => scorix.invoke<T.UpsertRes>("group:upsert", params),
  delete: (params: T.IdReq) => scorix.invoke<T.Empty>("group:delete", params),
};

export const setting = {
  list: (params: T.Empty) => scorix.invoke<T.SettingListRes>("setting:list", params),
  set: (params: T.SettingSetReq) => scorix.invoke<T.Empty>("setting:set", params),
  get: (params: T.SettingGetReq) => scorix.invoke<T.SettingGetRes>("setting:get", params),
};

