/**
 * Code generated by scorix. DO NOT EDIT.
 */
export interface ClientConnectReq {
  connection_id: string;
  database_index: number;
}

export interface ClientDisconnectReq {
  connection_id: string;
  database_index: number;
}

export interface ClientGeneralReq {
  connection_id: string;
  database_index: number;
}

export interface ClientGeneralRes {
  info: string;
  total_db: number;
  databases?: DbInfo[];
}

export interface ClientGetSlowQueryReq {
  connection_id: string;
  database_index: number;
}

export interface ClientGetSlowQueryRes {
  items?: SlowQueryItem[];
}

export interface ClientKeyCreateReq {
  connection_id: string;
  database_index: number;
  key: string;
  kind: string;
  ttl: number;
  value_string: string;
  value_json: string;
  value_list?: string[];
  value_hash?: KeyValue[];
  value_set?: string[];
  value_zset?: ZMember[];
  value_stream: StreamValue;
}

export interface ClientKeyDeleteReq {
  connection_id: string;
  database_index: number;
  key: string;
}

export interface ClientKeyNameUpdateReq {
  connection_id: string;
  database_index: number;
  current_name: string;
  new_name: string;
}

export interface ClientKeyTtlUpdateReq {
  connection_id: string;
  database_index: number;
  key_name: string;
  key_ttl: number;
}

export interface ClientKeyValueUpdateReq {
  connection_id: string;
  database_index: number;
  key: string;
  kind: string;
  value: string;
}

export interface ClientKeysDeleteByPrefixReq {
  connection_id: string;
  database_index: number;
  prefix: string;
  keys?: string[];
}

export interface ClientKeysDeleteByPrefixRes {
  total_deleted: number;
}

export interface ClientKeysMetadataReq {
  connection_id: string;
  database_index: number;
  keys?: string[];
}

export interface ClientKeysMetadataRes {
  items?: KeyMetadata[];
}

export interface ClientKeysScanByPrefixRes {
  keys?: string[];
  next_cursor: string;
}

export interface ClientLoadAllKeysReq {
  connection_id: string;
  database_index: number;
  prefix: string;
  count: number;
  cursor: string;
}

export interface ClientLoadAllKeysRes {
  keys?: string[];
  cursor: string;
}

export interface ClientLoadKeyDetailReq {
  connection_id: string;
  database_index: number;
  key: string;
}

export interface ClientLoadKeyDetailRes {
  key: string;
  value: string;
  kind: string;
  ttl: number;
  total: number;
}

export interface ClientLoadKeyValuePageReq {
  connection_id: string;
  database_index: number;
  key: string;
  kind: string;
  cursor: string;
  page_size: number;
}

export interface ClientLoadKeyValuePageRes {
  items?: KeyValuePageItem[];
  next_cursor: string;
  has_more: boolean;
}

export interface ClientSearchKeysReq {
  connection_id: string;
  database_index: number;
  prefix: string;
  count: number;
  cursor: string;
}

export interface ClientSearchKeysRes {
  keys?: string[];
}

export interface ConnectionListRes {
  items?: ConnectionReq[];
}

export interface ConnectionReq {
  id: string;
  mode: string;
  name: string;
  network: string;
  host: string;
  port: number;
  addrs: string;
  sentinel_master: string;
  sentinel_username: string;
  sentinel_password: string;
  sock: string;
  username: string;
  password: string;
  addr_mapping: string;
  exec_timeout: number;
  dial_timeout: number;
  key_size: number;
  ssh_enable: boolean;
  ssh_id: string;
  proxy_enable: boolean;
  proxy_id: string;
  tls_enable: boolean;
  tls_id: string;
  ssh: SshReq;
  proxy: ProxyReq;
  tls: TlsReq;
  group_id: string;
  last_db: number;
}

export interface DbInfo {
  index: number;
  name: string;
  keys: number;
  expires: number;
  avg_ttl: number;
}

export interface Empty {
}

export interface GroupItem {
  id: string;
  name: string;
  created_at: number;
  updated_at: number;
}

export interface GroupListRes {
  items?: GroupItem[];
}

export interface GroupUpsertReq {
  id: string;
  name: string;
}

export interface IdReq {
  id: string;
}

export interface KeyHashFieldDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  field: string;
}

export interface KeyListItemDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  index: number;
  value: string;
}

export interface KeyLoadReq {
  connection_id: string;
  database_index: number;
  key: string;
  cursor: string;
  count: number;
}

export interface KeyLoadRes {
  keys?: string[];
  cursor: string;
}

export interface KeyMetadata {
  key: string;
  type: string;
  ttl: number;
  size: number;
}

export interface KeySetMemberDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  member: string;
}

export interface KeyStreamEntryDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  entry_id: string;
}

export interface KeyValue {
  key: string;
  value: string;
}

export interface KeyValuePageItem {
  field: string;
  value: string;
  index: number;
  member: string;
  score: number;
  id: string;
}

export interface KeyZSetMemberDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  member: string;
}

export interface MonitorReq {
  connection_id: string;
  database_index: number;
}

export interface MonitorStatusRes {
  active: boolean;
}

export interface ProxyListRes {
  items?: ProxyReq[];
}

export interface ProxyReq {
  id: string;
  protocol: string;
  host: string;
  port: number;
  username: string;
  password: string;
}

export interface PubSubPublishReq {
  connection_id: string;
  database_index: number;
  channel: string;
  message: string;
}

export interface PubSubSubscribeReq {
  connection_id: string;
  database_index: number;
  channels?: string[];
}

export interface SettingGetReq {
  key: string;
}

export interface SettingGetRes {
  value: string;
}

export interface SettingItem {
  key: string;
  value: string;
}

export interface SettingListRes {
  items?: SettingItem[];
}

export interface SettingSetReq {
  key: string;
  value: string;
}

export interface SlowQueryItem {
  id: number;
  timestamp: number;
  duration: number;
  command?: string[];
  client_addr: string;
  client_name: string;
}

export interface SshListRes {
  items?: SshReq[];
}

export interface SshReq {
  id: string;
  host: string;
  port: number;
  username: string;
  kind: string;
  password: string;
  private_key: string;
  passphrase: string;
  timeout: number;
}

export interface StreamValue {
  id: string;
  values: string;
}

export interface SystemInfoRes {
  version: string;
  os: string;
  arch: string;
  runtime: string;
}

export interface TlsListRes {
  items?: TlsReq[];
}

export interface TlsReq {
  id: string;
  name: string;
  use_sni: boolean;
  server_name: string;
  verify: boolean;
  client_auth: boolean;
  ca_cert: string;
  cert: string;
  key: string;
}

export interface UpsertRes {
  id: string;
}

export interface ZMember {
  member: string;
  score: number;
}

