/**
 * Code generated by scorix. DO NOT EDIT.
 */
export interface AnalysisBucket {
  label: string;
  count: number;
}

export interface AnalysisMemory {
  used: number;
  peak: number;
  dataset: number;
  overhead: number;
  maxmemory: number;
  fragmentation: number;
  policy: string;
}

export interface AnalysisNode {
  addr: string;
  keys: number;
}

export interface AnalysisProfileEvent {
  phase: string;
  scanned: number;
  total: number;
  truncated: boolean;
  warnings?: string[];
  distrib_source: string;
  redis_version: string;
  memory: AnalysisMemory;
  ttl: AnalysisTtlStat;
  types?: AnalysisTypeStat[];
  distrib?: AnalysisSizeDistrib[];
  top_keys?: AnalysisTopKey[];
  nodes?: AnalysisNode[];
  recency_metric: string;
}

export interface AnalysisProfileReq {
  connection_id: string;
  database_index: number;
  mode: string;
  sample_size: number;
}

export interface AnalysisSizeDistrib {
  kind: string;
  unit: string;
  buckets?: AnalysisBucket[];
}

export interface AnalysisTopKey {
  key: string;
  kind: string;
  bytes: number;
  ttl_ms: number;
  recency: number;
}

export interface AnalysisTtlStat {
  total: number;
  with_ttl: number;
  avg_ttl_ms: number;
  buckets?: AnalysisBucket[];
}

export interface AnalysisTypeStat {
  kind: string;
  keys: number;
  bytes: number;
}

export interface ClientConnectReq {
  connection_id: string;
  database_index: number;
}

export interface ClientDisconnectReq {
  connection_id: string;
}

export interface ClientGeneralReq {
  connection_id: string;
  database_index: number;
}

export interface ClientGeneralRes {
  info: string;
  total_db: number;
  databases?: DbInfo[];
}

export interface ClientGetSlowQueryReq {
  connection_id: string;
  database_index: number;
}

export interface ClientGetSlowQueryRes {
  items?: SlowQueryItem[];
}

export interface ClientKeyCreateReq {
  connection_id: string;
  database_index: number;
  key: string;
  kind: string;
  ttl: number;
  value_string: string;
  value_json: string;
  value_list?: string[];
  value_hash?: KeyValue[];
  value_set?: string[];
  value_zset?: ZMember[];
  value_stream: StreamValue;
  value_graph: string;
}

export interface ClientKeyDeleteReq {
  connection_id: string;
  database_index: number;
  key: string;
}

export interface ClientKeyNameUpdateReq {
  connection_id: string;
  database_index: number;
  current_name: string;
  new_name: string;
}

export interface ClientKeyTtlUpdateReq {
  connection_id: string;
  database_index: number;
  key_name: string;
  key_ttl: number;
}

export interface ClientKeyValueUpdateReq {
  connection_id: string;
  database_index: number;
  key: string;
  kind: string;
  value: string;
}

export interface ClientKeysDeleteByPrefixReq {
  connection_id: string;
  database_index: number;
  prefix: string;
  keys?: string[];
}

export interface ClientKeysDeleteByPrefixRes {
  total_deleted: number;
}

export interface ClientKeysDeleteProgressEvent {
  connection_id: string;
  prefix: string;
  deleted: number;
  total: number;
  status: string;
}

export interface ClientKeysMetadataReq {
  connection_id: string;
  database_index: number;
  keys?: string[];
}

export interface ClientKeysMetadataRes {
  items?: KeyMetadata[];
}

export interface ClientKeysScanByPrefixRes {
  keys?: string[];
  next_cursor: string;
}

export interface ClientKeysSearchEvent {
  keys?: string[];
  scanned: number;
  matched: number;
  cursor: string;
  done: boolean;
  truncated: boolean;
}

export interface ClientKeysSearchReq {
  connection_id: string;
  database_index: number;
  filters?: KeyFilter[];
  match_all: boolean;
  key_type: string;
  scan_count: number;
  limit: number;
  cursor: string;
  budget_ms: number;
}

export interface ClientLoadAllKeysReq {
  connection_id: string;
  database_index: number;
  prefix: string;
  count: number;
  cursor: string;
}

export interface ClientLoadAllKeysRes {
  keys?: string[];
  cursor: string;
}

export interface ClientLoadKeyDetailReq {
  connection_id: string;
  database_index: number;
  key: string;
}

export interface ClientLoadKeyDetailRes {
  key: string;
  value: string;
  kind: string;
  ttl: number;
  total: number;
  encoding: string;
  size: number;
}

export interface ClientLoadKeyValuePageReq {
  connection_id: string;
  database_index: number;
  key: string;
  kind: string;
  cursor: string;
  page_size: number;
}

export interface ClientLoadKeyValuePageRes {
  items?: KeyValuePageItem[];
  next_cursor: string;
  has_more: boolean;
}

export interface ClientProbeReq {
  connection_id: string;
}

export interface ClientSearchKeysReq {
  connection_id: string;
  database_index: number;
  prefix: string;
  count: number;
  cursor: string;
}

export interface ClientSearchKeysRes {
  keys?: string[];
}

export interface ClientSetReadOnlyReq {
  connection_id: string;
  database_index: number;
  read_only: boolean;
}

export interface ClientStateEvent {
  connection_id: string;
  state: string;
  error: string;
  latency_ms: number;
  since: number;
}

export interface ClientStatesRes {
  items?: ClientStateEvent[];
}

export interface ConnectionListRes {
  items?: ConnectionReq[];
}

export interface ConnectionReq {
  id: string;
  mode: string;
  name: string;
  network: string;
  host: string;
  port: number;
  addrs: string;
  sentinel_master: string;
  sentinel_username: string;
  sentinel_password: string;
  sock: string;
  username: string;
  password: string;
  addr_mapping: string;
  exec_timeout: number;
  dial_timeout: number;
  key_size: number;
  ssh_enable: boolean;
  ssh_id: string;
  proxy_enable: boolean;
  proxy_id: string;
  tls_enable: boolean;
  tls_id: string;
  ssh: SshReq;
  proxy: ProxyReq;
  tls: TlsReq;
  group_id: string;
  last_db: number;
  read_only: boolean;
  color: string;
}

export interface ConsoleInputEvent {
  connection_id: string;
  database_index: number;
  id: string;
  command: string;
}

export interface ConsoleOutputEvent {
  connection_id: string;
  id: string;
  stdout: string;
  stderr: string;
}

export interface DbInfo {
  index: number;
  name: string;
  keys: number;
  expires: number;
  avg_ttl: number;
}

export interface Empty {
}

export interface GraphEdge {
  id: number;
  type: string;
  src: number;
  dst: number;
  properties: string;
}

export interface GraphNode {
  id: number;
  labels?: string[];
  properties: string;
}

export interface GraphQueryReq {
  connection_id: string;
  database_index: number;
  graph: string;
  query: string;
}

export interface GraphQueryRes {
  columns?: string[];
  rows?: GraphRow[];
  nodes?: GraphNode[];
  edges?: GraphEdge[];
  stats?: string[];
}

export interface GraphRow {
  cells?: string[];
}

export interface GraphSchemaReq {
  connection_id: string;
  database_index: number;
  graph: string;
}

export interface GraphSchemaRes {
  labels?: string[];
  relationships?: string[];
  properties?: string[];
  nodes: number;
  edges: number;
}

export interface GroupItem {
  id: string;
  name: string;
  created_at: number;
  updated_at: number;
  color: string;
}

export interface GroupListRes {
  items?: GroupItem[];
}

export interface GroupUpsertReq {
  id: string;
  name: string;
  color: string;
}

export interface IdReq {
  id: string;
}

export interface KeyFilter {
  pattern: string;
  mode: string;
  exclude: boolean;
  ignore_case: boolean;
}

export interface KeyHashFieldDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  field: string;
}

export interface KeyHashFieldUpdateReq {
  connection_id: string;
  database_index: number;
  key: string;
  field: string;
  new_field: string;
  value: string;
}

export interface KeyListItemDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  index: number;
  value: string;
}

export interface KeyListItemUpdateReq {
  connection_id: string;
  database_index: number;
  key: string;
  index: number;
  old_value: string;
  value: string;
}

export interface KeyLoadReq {
  connection_id: string;
  database_index: number;
  key: string;
  cursor: string;
  count: number;
}

export interface KeyLoadRes {
  keys?: string[];
  cursor: string;
}

export interface KeyMetadata {
  key: string;
  type: string;
  ttl: number;
  size: number;
}

export interface KeySetMemberDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  member: string;
}

export interface KeySetMemberUpdateReq {
  connection_id: string;
  database_index: number;
  key: string;
  member: string;
  new_member: string;
}

export interface KeyStreamEntryDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  entry_id: string;
}

export interface KeyValue {
  key: string;
  value: string;
}

export interface KeyValuePageItem {
  field: string;
  value: string;
  index: number;
  member: string;
  score: number;
  id: string;
}

export interface KeyZSetMemberDelReq {
  connection_id: string;
  database_index: number;
  key: string;
  member: string;
}

export interface KeyZSetMemberUpdateReq {
  connection_id: string;
  database_index: number;
  key: string;
  member: string;
  new_member: string;
  score: number;
}

export interface MonitorFrame {
  kind: string;
  connection_id: string;
  active: boolean;
  line: string;
}

export interface MonitorMessageEvent {
  connection_id: string;
  line: string;
}

export interface MonitorReq {
  connection_id: string;
  database_index: number;
}

export interface MonitorStatusEvent {
  connection_id: string;
  active: boolean;
}

export interface MonitorStatusRes {
  active: boolean;
}

export interface ProxyListRes {
  items?: ProxyReq[];
}

export interface ProxyReq {
  id: string;
  protocol: string;
  host: string;
  port: number;
  username: string;
  password: string;
}

export interface PubSubPublishReq {
  connection_id: string;
  database_index: number;
  channel: string;
  message: string;
}

export interface PubSubStreamReq {
  connection_id: string;
  database_index: number;
}

export interface PubSubSubscribeReq {
  connection_id: string;
  database_index: number;
  channels?: string[];
}

export interface PubsubMessageEvent {
  connection_id: string;
  channel: string;
  message: string;
  pattern: string;
}

export interface SearchPresetItem {
  id: string;
  name: string;
  filters?: KeyFilter[];
  match_all: boolean;
  key_type: string;
  created_at: number;
  updated_at: number;
}

export interface SearchPresetListRes {
  items?: SearchPresetItem[];
}

export interface SearchPresetUpsertReq {
  id: string;
  name: string;
  filters?: KeyFilter[];
  match_all: boolean;
  key_type: string;
}

export interface SettingGetReq {
  key: string;
}

export interface SettingGetRes {
  value: string;
}

export interface SettingItem {
  key: string;
  value: string;
}

export interface SettingListRes {
  items?: SettingItem[];
}

export interface SettingSetReq {
  key: string;
  value: string;
}

export interface SlowQueryItem {
  id: number;
  timestamp: number;
  duration: number;
  command?: string[];
  client_addr: string;
  client_name: string;
}

export interface SshListRes {
  items?: SshReq[];
}

export interface SshReq {
  id: string;
  host: string;
  port: number;
  username: string;
  kind: string;
  password: string;
  private_key: string;
  passphrase: string;
  timeout: number;
}

export interface StreamValue {
  id: string;
  values: string;
}

export interface SystemInfoRes {
  version: string;
  os: string;
  arch: string;
  runtime: string;
}

export interface TlsListRes {
  items?: TlsReq[];
}

export interface TlsReq {
  id: string;
  name: string;
  use_sni: boolean;
  server_name: string;
  verify: boolean;
  client_auth: boolean;
  ca_cert: string;
  cert: string;
  key: string;
}

export interface UpsertRes {
  id: string;
}

export interface ZMember {
  member: string;
  score: number;
}

