// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	connectionFindOneSQL  = "SELECT `id`,`mode`,`name`,`network`,`host`,`port`,`addrs`,`sentinel_master`,`sentinel_username`,`sentinel_password`,`sock`,`username`,`password`,`addr_mapping`,`last_db`,`exec_timeout`,`dial_timeout`,`key_size`,`group_id`,`ssh_enable`,`ssh_id`,`proxy_enable`,`proxy_id`,`tls_enable`,`tls_id`,`created_at`,`updated_at`,`deleted_at` FROM `connection` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	connectionFindAllSQL  = "SELECT `id`,`mode`,`name`,`network`,`host`,`port`,`addrs`,`sentinel_master`,`sentinel_username`,`sentinel_password`,`sock`,`username`,`password`,`addr_mapping`,`last_db`,`exec_timeout`,`dial_timeout`,`key_size`,`group_id`,`ssh_enable`,`ssh_id`,`proxy_enable`,`proxy_id`,`tls_enable`,`tls_id`,`created_at`,`updated_at`,`deleted_at` FROM `connection` WHERE `deleted_at` IS NULL"
	connectionFindManySQL = "SELECT `id`,`mode`,`name`,`network`,`host`,`port`,`addrs`,`sentinel_master`,`sentinel_username`,`sentinel_password`,`sock`,`username`,`password`,`addr_mapping`,`last_db`,`exec_timeout`,`dial_timeout`,`key_size`,`group_id`,`ssh_enable`,`ssh_id`,`proxy_enable`,`proxy_id`,`tls_enable`,`tls_id`,`created_at`,`updated_at`,`deleted_at` FROM `connection` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	connectionInsertSQL   = "INSERT INTO `connection` (`id`,`mode`,`name`,`network`,`host`,`port`,`addrs`,`sentinel_master`,`sentinel_username`,`sentinel_password`,`sock`,`username`,`password`,`addr_mapping`,`last_db`,`exec_timeout`,`dial_timeout`,`key_size`,`group_id`,`ssh_enable`,`ssh_id`,`proxy_enable`,`proxy_id`,`tls_enable`,`tls_id`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
	connectionUpdateSQL   = "UPDATE `connection` SET `mode` = ?, `name` = ?, `network` = ?, `host` = ?, `port` = ?, `addrs` = ?, `sentinel_master` = ?, `sentinel_username` = ?, `sentinel_password` = ?, `sock` = ?, `username` = ?, `password` = ?, `addr_mapping` = ?, `last_db` = ?, `exec_timeout` = ?, `dial_timeout` = ?, `key_size` = ?, `group_id` = ?, `ssh_enable` = ?, `ssh_id` = ?, `proxy_enable` = ?, `proxy_id` = ?, `tls_enable` = ?, `tls_id` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	connectionDeleteSQL   = "UPDATE `connection` SET `deleted_at` = ? WHERE `id` = ?"
)

type (
	// connectionModel — per-table CRUD only. Relations stitched in internal/logic/.
	connectionModel interface {
		Insert(ctx context.Context, data *Connection) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Connection, error)
		FindMany(ctx context.Context, ids []string) ([]*Connection, error)
		FindAll(ctx context.Context) ([]*Connection, error)
		Update(ctx context.Context, data *Connection) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultConnectionModel struct {
		conn func() scorixsqlx.Conn
	}

	Connection struct {
		ID               string       `db:"id" json:"id"`
		Mode             string       `db:"mode" json:"mode"`
		Name             string       `db:"name" json:"name"`
		Network          string       `db:"network" json:"network"`
		Host             string       `db:"host" json:"host"`
		Port             int64        `db:"port" json:"port"`
		Addrs            string       `db:"addrs" json:"addrs"`
		SentinelMaster   string       `db:"sentinel_master" json:"sentinel_master"`
		SentinelUsername string       `db:"sentinel_username" json:"sentinel_username"`
		SentinelPassword string       `db:"sentinel_password" json:"sentinel_password"`
		Sock             string       `db:"sock" json:"sock"`
		Username         string       `db:"username" json:"username"`
		Password         string       `db:"password" json:"password"`
		AddrMapping      string       `db:"addr_mapping" json:"addr_mapping"`
		LastDb           int64        `db:"last_db" json:"last_db"`
		ExecTimeout      int64        `db:"exec_timeout" json:"exec_timeout"`
		DialTimeout      int64        `db:"dial_timeout" json:"dial_timeout"`
		KeySize          int64        `db:"key_size" json:"key_size"`
		GroupID          string       `db:"group_id" json:"group_id"`
		SshEnable        int64        `db:"ssh_enable" json:"ssh_enable"`
		SshID            string       `db:"ssh_id" json:"ssh_id"`
		ProxyEnable      int64        `db:"proxy_enable" json:"proxy_enable"`
		ProxyID          string       `db:"proxy_id" json:"proxy_id"`
		TlsEnable        int64        `db:"tls_enable" json:"tls_enable"`
		TlsID            string       `db:"tls_id" json:"tls_id"`
		CreatedAt        time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt        time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt        sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultConnectionModel(conn func() scorixsqlx.Conn) *defaultConnectionModel {
	return &defaultConnectionModel{conn: conn}
}

func (m *defaultConnectionModel) Insert(ctx context.Context, data *Connection) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, connectionInsertSQL,
		data.ID,
		data.Mode,
		data.Name,
		data.Network,
		data.Host,
		data.Port,
		data.Addrs,
		data.SentinelMaster,
		data.SentinelUsername,
		data.SentinelPassword,
		data.Sock,
		data.Username,
		data.Password,
		data.AddrMapping,
		data.LastDb,
		data.ExecTimeout,
		data.DialTimeout,
		data.KeySize,
		data.GroupID,
		data.SshEnable,
		data.SshID,
		data.ProxyEnable,
		data.ProxyID,
		data.TlsEnable,
		data.TlsID,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultConnectionModel) FindOne(ctx context.Context, id string) (*Connection, error) {
	var resp Connection
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, connectionFindOneSQL, id)
	return &resp, err
}

func (m *defaultConnectionModel) FindMany(ctx context.Context, ids []string) ([]*Connection, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(connectionFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*Connection
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultConnectionModel) FindAll(ctx context.Context) ([]*Connection, error) {
	var resp []*Connection
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, connectionFindAllSQL)
	return resp, err
}

func (m *defaultConnectionModel) Update(ctx context.Context, data *Connection) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, connectionUpdateSQL,
		data.Mode,
		data.Name,
		data.Network,
		data.Host,
		data.Port,
		data.Addrs,
		data.SentinelMaster,
		data.SentinelUsername,
		data.SentinelPassword,
		data.Sock,
		data.Username,
		data.Password,
		data.AddrMapping,
		data.LastDb,
		data.ExecTimeout,
		data.DialTimeout,
		data.KeySize,
		data.GroupID,
		data.SshEnable,
		data.SshID,
		data.ProxyEnable,
		data.ProxyID,
		data.TlsEnable,
		data.TlsID,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultConnectionModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, connectionDeleteSQL, time.Now(), id)
	return err
}
