// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	groupFindOneSQL  = "SELECT `id`,`name`,`created_at`,`updated_at`,`deleted_at` FROM `group` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	groupFindAllSQL  = "SELECT `id`,`name`,`created_at`,`updated_at`,`deleted_at` FROM `group` WHERE `deleted_at` IS NULL"
	groupFindManySQL = "SELECT `id`,`name`,`created_at`,`updated_at`,`deleted_at` FROM `group` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	groupInsertSQL   = "INSERT INTO `group` (`id`,`name`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?)"
	groupUpdateSQL   = "UPDATE `group` SET `name` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	groupDeleteSQL   = "UPDATE `group` SET `deleted_at` = ? WHERE `id` = ?"
)

type (
	// groupModel — per-table CRUD only. Relations stitched in internal/logic/.
	groupModel interface {
		Insert(ctx context.Context, data *Group) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Group, error)
		FindMany(ctx context.Context, ids []string) ([]*Group, error)
		FindAll(ctx context.Context) ([]*Group, error)
		Update(ctx context.Context, data *Group) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultGroupModel struct {
		conn func() scorixsqlx.Conn
	}

	Group struct {
		ID        string       `db:"id" json:"id"`
		Name      string       `db:"name" json:"name"`
		CreatedAt time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultGroupModel(conn func() scorixsqlx.Conn) *defaultGroupModel {
	return &defaultGroupModel{conn: conn}
}

func (m *defaultGroupModel) Insert(ctx context.Context, data *Group) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, groupInsertSQL,
		data.ID,
		data.Name,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultGroupModel) FindOne(ctx context.Context, id string) (*Group, error) {
	var resp Group
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, groupFindOneSQL, id)
	return &resp, err
}

func (m *defaultGroupModel) FindMany(ctx context.Context, ids []string) ([]*Group, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(groupFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*Group
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultGroupModel) FindAll(ctx context.Context) ([]*Group, error) {
	var resp []*Group
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, groupFindAllSQL)
	return resp, err
}

func (m *defaultGroupModel) Update(ctx context.Context, data *Group) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, groupUpdateSQL,
		data.Name,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultGroupModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, groupDeleteSQL, time.Now(), id)
	return err
}
