// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	proxyFindOneSQL  = "SELECT `id`,`protocol`,`host`,`port`,`username`,`password`,`created_at`,`updated_at`,`deleted_at` FROM `proxy` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	proxyFindAllSQL  = "SELECT `id`,`protocol`,`host`,`port`,`username`,`password`,`created_at`,`updated_at`,`deleted_at` FROM `proxy` WHERE `deleted_at` IS NULL"
	proxyFindManySQL = "SELECT `id`,`protocol`,`host`,`port`,`username`,`password`,`created_at`,`updated_at`,`deleted_at` FROM `proxy` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	proxyInsertSQL   = "INSERT INTO `proxy` (`id`,`protocol`,`host`,`port`,`username`,`password`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?,?,?,?)"
	proxyUpdateSQL   = "UPDATE `proxy` SET `protocol` = ?, `host` = ?, `port` = ?, `username` = ?, `password` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	proxyDeleteSQL   = "UPDATE `proxy` SET `deleted_at` = ? WHERE `id` = ?"
)

type (
	// proxyModel — per-table CRUD only. Relations stitched in internal/logic/.
	proxyModel interface {
		Insert(ctx context.Context, data *Proxy) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Proxy, error)
		FindMany(ctx context.Context, ids []string) ([]*Proxy, error)
		FindAll(ctx context.Context) ([]*Proxy, error)
		Update(ctx context.Context, data *Proxy) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultProxyModel struct {
		conn func() scorixsqlx.Conn
	}

	Proxy struct {
		ID        string       `db:"id" json:"id"`
		Protocol  string       `db:"protocol" json:"protocol"`
		Host      string       `db:"host" json:"host"`
		Port      int64        `db:"port" json:"port"`
		Username  string       `db:"username" json:"username"`
		Password  string       `db:"password" json:"password"`
		CreatedAt time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultProxyModel(conn func() scorixsqlx.Conn) *defaultProxyModel {
	return &defaultProxyModel{conn: conn}
}

func (m *defaultProxyModel) Insert(ctx context.Context, data *Proxy) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, proxyInsertSQL,
		data.ID,
		data.Protocol,
		data.Host,
		data.Port,
		data.Username,
		data.Password,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultProxyModel) FindOne(ctx context.Context, id string) (*Proxy, error) {
	var resp Proxy
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, proxyFindOneSQL, id)
	return &resp, err
}

func (m *defaultProxyModel) FindMany(ctx context.Context, ids []string) ([]*Proxy, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(proxyFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*Proxy
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultProxyModel) FindAll(ctx context.Context) ([]*Proxy, error) {
	var resp []*Proxy
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, proxyFindAllSQL)
	return resp, err
}

func (m *defaultProxyModel) Update(ctx context.Context, data *Proxy) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, proxyUpdateSQL,
		data.Protocol,
		data.Host,
		data.Port,
		data.Username,
		data.Password,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultProxyModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, proxyDeleteSQL, time.Now(), id)
	return err
}
