// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	searchPresetFindOneSQL  = "SELECT `id`,`name`,`filters`,`match_all`,`key_type`,`created_at`,`updated_at`,`deleted_at` FROM `search_preset` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	searchPresetFindAllSQL  = "SELECT `id`,`name`,`filters`,`match_all`,`key_type`,`created_at`,`updated_at`,`deleted_at` FROM `search_preset` WHERE `deleted_at` IS NULL"
	searchPresetFindManySQL = "SELECT `id`,`name`,`filters`,`match_all`,`key_type`,`created_at`,`updated_at`,`deleted_at` FROM `search_preset` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	searchPresetInsertSQL   = "INSERT INTO `search_preset` (`id`,`name`,`filters`,`match_all`,`key_type`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?,?,?)"
	searchPresetUpdateSQL   = "UPDATE `search_preset` SET `name` = ?, `filters` = ?, `match_all` = ?, `key_type` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	searchPresetDeleteSQL   = "UPDATE `search_preset` SET `deleted_at` = ? WHERE `id` = ?"
)

type (
	// searchPresetModel — per-table CRUD only. Relations stitched in internal/logic/.
	searchPresetModel interface {
		Insert(ctx context.Context, data *SearchPreset) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*SearchPreset, error)
		FindMany(ctx context.Context, ids []string) ([]*SearchPreset, error)
		FindAll(ctx context.Context) ([]*SearchPreset, error)
		Update(ctx context.Context, data *SearchPreset) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultSearchPresetModel struct {
		conn func() scorixsqlx.Conn
	}

	SearchPreset struct {
		ID        string       `db:"id" json:"id"`
		Name      string       `db:"name" json:"name"`
		Filters   string       `db:"filters" json:"filters"`
		MatchAll  int64        `db:"match_all" json:"match_all"`
		KeyType   string       `db:"key_type" json:"key_type"`
		CreatedAt time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultSearchPresetModel(conn func() scorixsqlx.Conn) *defaultSearchPresetModel {
	return &defaultSearchPresetModel{conn: conn}
}

func (m *defaultSearchPresetModel) Insert(ctx context.Context, data *SearchPreset) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, searchPresetInsertSQL,
		data.ID,
		data.Name,
		data.Filters,
		data.MatchAll,
		data.KeyType,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultSearchPresetModel) FindOne(ctx context.Context, id string) (*SearchPreset, error) {
	var resp SearchPreset
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, searchPresetFindOneSQL, id)
	return &resp, err
}

func (m *defaultSearchPresetModel) FindMany(ctx context.Context, ids []string) ([]*SearchPreset, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(searchPresetFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*SearchPreset
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultSearchPresetModel) FindAll(ctx context.Context) ([]*SearchPreset, error) {
	var resp []*SearchPreset
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, searchPresetFindAllSQL)
	return resp, err
}

func (m *defaultSearchPresetModel) Update(ctx context.Context, data *SearchPreset) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, searchPresetUpdateSQL,
		data.Name,
		data.Filters,
		data.MatchAll,
		data.KeyType,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultSearchPresetModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, searchPresetDeleteSQL, time.Now(), id)
	return err
}
