// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	settingFindOneSQL      = "SELECT `id`,`key`,`value`,`created_at`,`updated_at`,`deleted_at` FROM `setting` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	settingFindAllSQL      = "SELECT `id`,`key`,`value`,`created_at`,`updated_at`,`deleted_at` FROM `setting` WHERE `deleted_at` IS NULL"
	settingFindManySQL     = "SELECT `id`,`key`,`value`,`created_at`,`updated_at`,`deleted_at` FROM `setting` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	settingInsertSQL       = "INSERT INTO `setting` (`id`,`key`,`value`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?)"
	settingUpdateSQL       = "UPDATE `setting` SET `key` = ?, `value` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	settingDeleteSQL       = "UPDATE `setting` SET `deleted_at` = ? WHERE `id` = ?"
	settingFindOneByKeySQL = "SELECT `id`,`key`,`value`,`created_at`,`updated_at`,`deleted_at` FROM `setting` WHERE `key` = ? AND `deleted_at` IS NULL LIMIT 1"
)

type (
	// settingModel — per-table CRUD only. Relations stitched in internal/logic/.
	settingModel interface {
		Insert(ctx context.Context, data *Setting) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Setting, error)
		FindMany(ctx context.Context, ids []string) ([]*Setting, error)
		FindAll(ctx context.Context) ([]*Setting, error)
		FindOneByKey(ctx context.Context, key string) (*Setting, error)
		Update(ctx context.Context, data *Setting) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultSettingModel struct {
		conn func() scorixsqlx.Conn
	}

	Setting struct {
		ID        string       `db:"id" json:"id"`
		Key       string       `db:"key" json:"key"`
		Value     string       `db:"value" json:"value"`
		CreatedAt time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultSettingModel(conn func() scorixsqlx.Conn) *defaultSettingModel {
	return &defaultSettingModel{conn: conn}
}

func (m *defaultSettingModel) Insert(ctx context.Context, data *Setting) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, settingInsertSQL,
		data.ID,
		data.Key,
		data.Value,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultSettingModel) FindOne(ctx context.Context, id string) (*Setting, error) {
	var resp Setting
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, settingFindOneSQL, id)
	return &resp, err
}

func (m *defaultSettingModel) FindMany(ctx context.Context, ids []string) ([]*Setting, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(settingFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*Setting
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultSettingModel) FindAll(ctx context.Context) ([]*Setting, error) {
	var resp []*Setting
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, settingFindAllSQL)
	return resp, err
}

func (m *defaultSettingModel) FindOneByKey(ctx context.Context, key string) (*Setting, error) {
	var resp Setting
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, settingFindOneByKeySQL, key)
	return &resp, err
}

func (m *defaultSettingModel) Update(ctx context.Context, data *Setting) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, settingUpdateSQL,
		data.Key,
		data.Value,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultSettingModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, settingDeleteSQL, time.Now(), id)
	return err
}
