// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	sshFindOneSQL  = "SELECT `id`,`host`,`port`,`username`,`kind`,`password`,`private_key`,`passphrase`,`timeout`,`created_at`,`updated_at`,`deleted_at` FROM `ssh` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	sshFindAllSQL  = "SELECT `id`,`host`,`port`,`username`,`kind`,`password`,`private_key`,`passphrase`,`timeout`,`created_at`,`updated_at`,`deleted_at` FROM `ssh` WHERE `deleted_at` IS NULL"
	sshFindManySQL = "SELECT `id`,`host`,`port`,`username`,`kind`,`password`,`private_key`,`passphrase`,`timeout`,`created_at`,`updated_at`,`deleted_at` FROM `ssh` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	sshInsertSQL   = "INSERT INTO `ssh` (`id`,`host`,`port`,`username`,`kind`,`password`,`private_key`,`passphrase`,`timeout`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"
	sshUpdateSQL   = "UPDATE `ssh` SET `host` = ?, `port` = ?, `username` = ?, `kind` = ?, `password` = ?, `private_key` = ?, `passphrase` = ?, `timeout` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	sshDeleteSQL   = "UPDATE `ssh` SET `deleted_at` = ? WHERE `id` = ?"
)

type (
	// sshModel — per-table CRUD only. Relations stitched in internal/logic/.
	sshModel interface {
		Insert(ctx context.Context, data *Ssh) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Ssh, error)
		FindMany(ctx context.Context, ids []string) ([]*Ssh, error)
		FindAll(ctx context.Context) ([]*Ssh, error)
		Update(ctx context.Context, data *Ssh) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultSshModel struct {
		conn func() scorixsqlx.Conn
	}

	Ssh struct {
		ID         string       `db:"id" json:"id"`
		Host       string       `db:"host" json:"host"`
		Port       int64        `db:"port" json:"port"`
		Username   string       `db:"username" json:"username"`
		Kind       string       `db:"kind" json:"kind"`
		Password   string       `db:"password" json:"password"`
		PrivateKey string       `db:"private_key" json:"private_key"`
		Passphrase string       `db:"passphrase" json:"passphrase"`
		Timeout    int64        `db:"timeout" json:"timeout"`
		CreatedAt  time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt  time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultSshModel(conn func() scorixsqlx.Conn) *defaultSshModel {
	return &defaultSshModel{conn: conn}
}

func (m *defaultSshModel) Insert(ctx context.Context, data *Ssh) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, sshInsertSQL,
		data.ID,
		data.Host,
		data.Port,
		data.Username,
		data.Kind,
		data.Password,
		data.PrivateKey,
		data.Passphrase,
		data.Timeout,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultSshModel) FindOne(ctx context.Context, id string) (*Ssh, error) {
	var resp Ssh
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, sshFindOneSQL, id)
	return &resp, err
}

func (m *defaultSshModel) FindMany(ctx context.Context, ids []string) ([]*Ssh, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(sshFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*Ssh
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultSshModel) FindAll(ctx context.Context) ([]*Ssh, error) {
	var resp []*Ssh
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, sshFindAllSQL)
	return resp, err
}

func (m *defaultSshModel) Update(ctx context.Context, data *Ssh) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, sshUpdateSQL,
		data.Host,
		data.Port,
		data.Username,
		data.Kind,
		data.Password,
		data.PrivateKey,
		data.Passphrase,
		data.Timeout,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultSshModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, sshDeleteSQL, time.Now(), id)
	return err
}
