// Code generated by scorix. DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"

	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
)

const (
	tlsFindOneSQL  = "SELECT `id`,`name`,`use_sni`,`server_name`,`verify`,`client_auth`,`ca_cert`,`cert`,`key`,`created_at`,`updated_at`,`deleted_at` FROM `tls` WHERE `id` = ? AND `deleted_at` IS NULL LIMIT 1"
	tlsFindAllSQL  = "SELECT `id`,`name`,`use_sni`,`server_name`,`verify`,`client_auth`,`ca_cert`,`cert`,`key`,`created_at`,`updated_at`,`deleted_at` FROM `tls` WHERE `deleted_at` IS NULL"
	tlsFindManySQL = "SELECT `id`,`name`,`use_sni`,`server_name`,`verify`,`client_auth`,`ca_cert`,`cert`,`key`,`created_at`,`updated_at`,`deleted_at` FROM `tls` WHERE `id` IN (?) AND `deleted_at` IS NULL"
	tlsInsertSQL   = "INSERT INTO `tls` (`id`,`name`,`use_sni`,`server_name`,`verify`,`client_auth`,`ca_cert`,`cert`,`key`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"
	tlsUpdateSQL   = "UPDATE `tls` SET `name` = ?, `use_sni` = ?, `server_name` = ?, `verify` = ?, `client_auth` = ?, `ca_cert` = ?, `cert` = ?, `key` = ?, `updated_at` = ?, `deleted_at` = ? WHERE `id` = ?"
	tlsDeleteSQL   = "UPDATE `tls` SET `deleted_at` = ? WHERE `id` = ?"
)

type (
	// tlsModel — per-table CRUD only. Relations stitched in internal/logic/.
	tlsModel interface {
		Insert(ctx context.Context, data *Tls) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Tls, error)
		FindMany(ctx context.Context, ids []string) ([]*Tls, error)
		FindAll(ctx context.Context) ([]*Tls, error)
		Update(ctx context.Context, data *Tls) error
		Delete(ctx context.Context, id string) error
	}

	// conn is a provider (not a bound handle) so callers can wire models in
	// NewServiceContext before OnLoad opens the DB. scorixsqlx.From(ctx, m.conn)
	// substitutes the *sqlx.Tx attached by Module.WithTx when present.
	defaultTlsModel struct {
		conn func() scorixsqlx.Conn
	}

	Tls struct {
		ID         string       `db:"id" json:"id"`
		Name       string       `db:"name" json:"name"`
		UseSni     int64        `db:"use_sni" json:"use_sni"`
		ServerName string       `db:"server_name" json:"server_name"`
		Verify     int64        `db:"verify" json:"verify"`
		ClientAuth int64        `db:"client_auth" json:"client_auth"`
		CaCert     string       `db:"ca_cert" json:"ca_cert"`
		Cert       string       `db:"cert" json:"cert"`
		Key        string       `db:"key" json:"key"`
		CreatedAt  time.Time    `db:"created_at" json:"created_at"`
		UpdatedAt  time.Time    `db:"updated_at" json:"updated_at"`
		DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
	}
)

func newDefaultTlsModel(conn func() scorixsqlx.Conn) *defaultTlsModel {
	return &defaultTlsModel{conn: conn}
}

func (m *defaultTlsModel) Insert(ctx context.Context, data *Tls) (sql.Result, error) {
	if data.ID == "" {
		data.ID = uuid.NewString()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = time.Now()
	return scorixsqlx.From(ctx, m.conn).ExecContext(ctx, tlsInsertSQL,
		data.ID,
		data.Name,
		data.UseSni,
		data.ServerName,
		data.Verify,
		data.ClientAuth,
		data.CaCert,
		data.Cert,
		data.Key,
		data.CreatedAt,
		data.UpdatedAt,
		data.DeletedAt,
	)
}

func (m *defaultTlsModel) FindOne(ctx context.Context, id string) (*Tls, error) {
	var resp Tls
	err := sqlx.GetContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, tlsFindOneSQL, id)
	return &resp, err
}

func (m *defaultTlsModel) FindMany(ctx context.Context, ids []string) ([]*Tls, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	conn := scorixsqlx.From(ctx, m.conn)
	query, args, err := sqlx.In(tlsFindManySQL, ids)
	if err != nil {
		return nil, err
	}
	query = conn.Rebind(query)
	var resp []*Tls
	err = sqlx.SelectContext(ctx, conn, &resp, query, args...)
	return resp, err
}

func (m *defaultTlsModel) FindAll(ctx context.Context) ([]*Tls, error) {
	var resp []*Tls
	err := sqlx.SelectContext(ctx, scorixsqlx.From(ctx, m.conn), &resp, tlsFindAllSQL)
	return resp, err
}

func (m *defaultTlsModel) Update(ctx context.Context, data *Tls) error {
	data.UpdatedAt = time.Now()
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, tlsUpdateSQL,
		data.Name,
		data.UseSni,
		data.ServerName,
		data.Verify,
		data.ClientAuth,
		data.CaCert,
		data.Cert,
		data.Key,
		data.UpdatedAt,
		data.DeletedAt,
		data.ID,
	)
	return err
}

func (m *defaultTlsModel) Delete(ctx context.Context, id string) error {
	_, err := scorixsqlx.From(ctx, m.conn).ExecContext(ctx, tlsDeleteSQL, time.Now(), id)
	return err
}
