// Code generated by scorix.
package client

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ConnectLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewConnectLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ConnectLogic {
	return &ConnectLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ConnectLogic) Connect(params *types.ClientConnectReq) (*types.Empty, error) {
	conn, err := l.svcCtx.ConnectionModel.FindOne(l.ctx, params.ConnectionId)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("connection not found: %s", params.ConnectionId)
		}
		return nil, fmt.Errorf("connection not found: %w", err)
	}

	var sshCfg *model.Ssh
	if conn.SshEnable > 0 && conn.SshID != "" {
		sshCfg, err = l.svcCtx.SshModel.FindOne(l.ctx, conn.SshID)
		if err != nil {
			return nil, fmt.Errorf("ssh config %s: %w", conn.SshID, err)
		}
	}
	var proxyCfg *model.Proxy
	if conn.ProxyEnable > 0 && conn.ProxyID != "" {
		proxyCfg, err = l.svcCtx.ProxyModel.FindOne(l.ctx, conn.ProxyID)
		if err != nil {
			return nil, fmt.Errorf("proxy config %s: %w", conn.ProxyID, err)
		}
	}
	var tlsCfg *model.Tls
	if conn.TlsEnable > 0 && conn.TlsID != "" {
		tlsCfg, err = l.svcCtx.TlsModel.FindOne(l.ctx, conn.TlsID)
		if err != nil {
			return nil, fmt.Errorf("tls config %s: %w", conn.TlsID, err)
		}
	}

	// Skip Update when LastDb unchanged to avoid bumping UpdatedAt and invalidating the cached client.
	if int32(conn.LastDb) != params.DatabaseIndex {
		conn.LastDb = int64(params.DatabaseIndex)
		if err := l.svcCtx.ConnectionModel.Update(l.ctx, conn); err != nil {
			return nil, fmt.Errorf("persist last_db: %w", err)
		}
	}

	if _, err := l.svcCtx.RedisManager.Add(conn, sshCfg, proxyCfg, tlsCfg, int(params.DatabaseIndex)); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
