// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ConsoleConnectLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewConsoleConnectLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ConsoleConnectLogic {
	return &ConsoleConnectLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ConsoleConnectLogic) ConsoleConnect(params *types.ClientConnectReq) (*types.Empty, error) {
	if _, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex)); err != nil {
		return nil, err
	}
	return &types.Empty{}, nil
}
