// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type DisconnectLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewDisconnectLogic(ctx context.Context, svcCtx *svc.ServiceContext) *DisconnectLogic {
	return &DisconnectLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *DisconnectLogic) Disconnect(params *types.ClientDisconnectReq) (*types.Empty, error) {
	l.svcCtx.RedisManager.RemoveConnection(params.ConnectionId)
	return &types.Empty{}, nil
}
