// Code generated by scorix.
package client

import (
	"context"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type DisconnectLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewDisconnectLogic(ctx context.Context, svcCtx *svc.ServiceContext) *DisconnectLogic {
	return &DisconnectLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *DisconnectLogic) Disconnect(params *types.ClientDisconnectReq) (*types.Empty, error) {
	if err := l.svcCtx.RedisManager.Remove(params.ConnectionId, int(params.DatabaseIndex)); err != nil {
		return nil, fmt.Errorf("disconnect failed: %w", err)
	}

	return &types.Empty{}, nil
}
