// Code generated by scorix.
package client

import (
	"context"
	"strconv"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type GeneralLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewGeneralLogic(ctx context.Context, svcCtx *svc.ServiceContext) *GeneralLogic {
	return &GeneralLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *GeneralLogic) General(params *types.ClientGeneralReq) (*types.ClientGeneralRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	infoRaw, err := cli.Rdb.Info(l.ctx).Result()
	if err != nil {
		return nil, err
	}

	dbCount := 16
	configRes, _ := cli.Rdb.ConfigGet(l.ctx, "databases").Result()
	if val, ok := configRes["databases"]; ok {
		if c, err := strconv.Atoi(val); err == nil {
			dbCount = c
		}
	}

	keyspace, _ := cli.Rdb.Info(l.ctx, "keyspace").Result()
	databases := make([]types.DbInfo, 0)
	activeDbs := make(map[int]types.DbInfo)

	lines := strings.Split(keyspace, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "db") {
			parts := strings.SplitN(line, ":", 2)
			if len(parts) == 2 {
				dbIdxStr := strings.TrimPrefix(parts[0], "db")
				dbIdx, _ := strconv.Atoi(dbIdxStr)

				dbInfo := types.DbInfo{Index: int32(dbIdx)}
				stats := strings.Split(parts[1], ",")
				for _, s := range stats {
					kv := strings.SplitN(strings.TrimSpace(s), "=", 2)
					if len(kv) == 2 {
						val, _ := strconv.ParseInt(kv[1], 10, 64)
						switch kv[0] {
						case "keys":
							dbInfo.Keys = int32(val)
						case "expires":
							dbInfo.Expires = int32(val)
						case "avg_ttl":
							dbInfo.AvgTtl = val
						}
					}
				}
				activeDbs[dbIdx] = dbInfo
			}
		}
	}

	for i := 0; i < dbCount; i++ {
		if info, ok := activeDbs[i]; ok {
			databases = append(databases, info)
		} else {
			databases = append(databases, types.DbInfo{Index: int32(i)})
		}
	}

	return &types.ClientGeneralRes{
		Info:      infoRaw,
		TotalDb:   int32(dbCount),
		Databases: databases,
	}, nil
}
