// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type GetSlowQueryLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewGetSlowQueryLogic(ctx context.Context, svcCtx *svc.ServiceContext) *GetSlowQueryLogic {
	return &GetSlowQueryLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *GetSlowQueryLogic) GetSlowQuery(params *types.ClientGetSlowQueryReq) (*types.ClientGetSlowQueryRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	logs, err := cli.Rdb.SlowLogGet(l.ctx, 1000).Result()
	if err != nil {
		return nil, err
	}

	items := make([]types.SlowQueryItem, len(logs))
	for i, log := range logs {
		items[i] = types.SlowQueryItem{
			Id:         log.ID,
			Timestamp:  log.Time.Unix(),
			Duration:   int64(log.Duration),
			Command:    log.Args,
			ClientAddr: log.ClientAddr,
			ClientName: log.ClientName,
		}
	}

	return &types.ClientGetSlowQueryRes{
		Items: items,
	}, nil
}
