// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeyNameUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeyNameUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeyNameUpdateLogic {
	return &KeyNameUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeyNameUpdateLogic) KeyNameUpdate(params *types.ClientKeyNameUpdateReq) (*types.Empty, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	err = cli.Rdb.Rename(l.ctx, params.CurrentName, params.NewName).Err()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
