// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeyDeleteLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeyDeleteLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeyDeleteLogic {
	return &KeyDeleteLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeyDeleteLogic) KeyDelete(params *types.ClientKeyDeleteReq) (*types.Empty, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	err = cli.Rdb.Del(l.ctx, params.Key).Err()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
