// Code generated by scorix.
package client

import (
	"context"
	"encoding/json"
	"strings"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeyCreateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeyCreateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeyCreateLogic {
	return &KeyCreateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeyCreateLogic) KeyCreate(params *types.ClientKeyCreateReq) (*types.Empty, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	var expiration time.Duration
	if params.Ttl < 0 {
		if expiration, err = cli.Rdb.PTTL(l.ctx, params.Key).Result(); err != nil {
			expiration = redis.KeepTTL
		}
	} else {
		expiration = time.Duration(params.Ttl) * time.Second
	}

	switch strings.ToLower(params.Kind) {
	case "string":
		_, err = cli.Rdb.Set(l.ctx, params.Key, params.ValueString, expiration).Result()
	case "list":
		if len(params.ValueList) > 0 {
			valAny := make([]any, len(params.ValueList))
			for i, v := range params.ValueList {
				valAny[i] = v
			}
			err = cli.Rdb.LPush(l.ctx, params.Key, valAny...).Err()
			if err == nil && expiration > 0 {
				cli.Rdb.Expire(l.ctx, params.Key, expiration)
			}
		}
	case "hash":
		if len(params.ValueHash) > 0 {
			_, err = cli.Rdb.Pipelined(l.ctx, func(pipe redis.Pipeliner) error {
				for _, kv := range params.ValueHash {
					pipe.HSet(l.ctx, params.Key, kv.Key, kv.Value)
				}
				if expiration > 0 {
					pipe.Expire(l.ctx, params.Key, expiration)
				}
				return nil
			})
		}
	case "set":
		if len(params.ValueSet) > 0 {
			valAny := make([]any, len(params.ValueSet))
			for i, v := range params.ValueSet {
				valAny[i] = v
			}
			err = cli.Rdb.SAdd(l.ctx, params.Key, valAny...).Err()
			if err == nil && expiration > 0 {
				cli.Rdb.Expire(l.ctx, params.Key, expiration)
			}
		}
	case "zset":
		if len(params.ValueZset) > 0 {
			var members []redis.Z
			for _, m := range params.ValueZset {
				members = append(members, redis.Z{
					Member: m.Member,
					Score:  m.Score,
				})
			}
			err = cli.Rdb.ZAdd(l.ctx, params.Key, members...).Err()
			if err == nil && expiration > 0 {
				cli.Rdb.Expire(l.ctx, params.Key, expiration)
			}
		}
	case "stream":
		if params.ValueStream.Values != "" {
			var values map[string]any
			_ = json.Unmarshal([]byte(params.ValueStream.Values), &values)
			err = cli.Rdb.XAdd(l.ctx, &redis.XAddArgs{
				Stream: params.Key,
				ID:     params.ValueStream.Id,
				Values: values,
			}).Err()
			if err == nil && expiration > 0 {
				cli.Rdb.Expire(l.ctx, params.Key, expiration)
			}
		}
	case "json", "rejson", "rejson-rl":
		err = cli.Rdb.JSONSet(l.ctx, params.Key, ".", params.ValueJson).Err()
		if err == nil && expiration > 0 {
			cli.Rdb.Expire(l.ctx, params.Key, expiration)
		}
	}

	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
