// Code generated by scorix.
package client

import (
	"context"
	"time"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeyTtlUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeyTtlUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeyTtlUpdateLogic {
	return &KeyTtlUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeyTtlUpdateLogic) KeyTtlUpdate(params *types.ClientKeyTtlUpdateReq) (*types.Empty, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	if params.KeyTtl >= 0 {
		err = cli.Rdb.Expire(l.ctx, params.KeyName, time.Duration(params.KeyTtl)*time.Second).Err()
		if err != nil {
			return nil, err
		}
	} else {
		err = cli.Rdb.Persist(l.ctx, params.KeyName).Err()
		if err != nil {
			return nil, err
		}
	}

	return &types.Empty{}, nil
}
