// Code generated by scorix.
package client

import (
	"context"

	"strconv"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeysScanByPrefixLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeysScanByPrefixLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeysScanByPrefixLogic {
	return &KeysScanByPrefixLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeysScanByPrefixLogic) KeysScanByPrefix(params *types.ClientKeysDeleteByPrefixReq) (*types.ClientKeysScanByPrefixRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	match := params.Prefix + "*"
	limit := int64(1000)

	keys, nextCursor, err := cli.Rdb.Scan(l.ctx, 0, match, limit).Result()
	if err != nil {
		return nil, err
	}

	return &types.ClientKeysScanByPrefixRes{
		Keys:       keys,
		NextCursor: strconv.FormatUint(nextCursor, 10),
	}, nil
}
