// Code generated by scorix.
package client

import (
	"context"
	"strconv"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/scorix/app"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/keyfilter"
	"github.com/tradalab/rdms/pkg/util"
)

const (
	defaultScanCount       = 1000
	defaultSearchLimit     = 10000
	defaultSearchBudget    = 15 * time.Second
	searchProgressInterval = 250 * time.Millisecond
	searchEmitBatch        = 200
)

type KeysSearchLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeysSearchLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeysSearchLogic {
	return &KeysSearchLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeysSearchLogic) KeysSearch(req *types.ClientKeysSearchReq, out app.Sink[types.ClientKeysSearchEvent]) error {
	clauses := make([]keyfilter.Clause, 0, len(req.Filters))
	for _, f := range req.Filters {
		clauses = append(clauses, keyfilter.Clause{
			Pattern:    f.Pattern,
			Mode:       f.Mode,
			Exclude:    f.Exclude,
			IgnoreCase: f.IgnoreCase,
		})
	}

	filter, err := keyfilter.Compile(clauses, req.MatchAll)
	if err != nil {
		return err // a bad regex is the user's typo, not a server fault: surface it verbatim
	}

	cli, err := l.svcCtx.RedisManager.Get(req.ConnectionId, int(req.DatabaseIndex))
	if err != nil {
		return err
	}

	cursor, err := parseSearchCursor(req.Cursor)
	if err != nil {
		return err
	}

	opts := searchOptions{
		match:     filter.Pushdown(),
		keyType:   req.KeyType,
		scanCount: req.ScanCount,
		limit:     req.Limit,
		budget:    time.Duration(req.BudgetMs) * time.Millisecond,
		cursor:    cursor,
	}

	return scanFiltered(out.Context(), cli.Rdb, filter, opts, out.Send)
}

type searchOptions struct {
	match     string
	keyType   string
	scanCount int64
	limit     int64
	budget    time.Duration
	cursor    uint64
}

func scanFiltered(
	ctx context.Context,
	rdb redis.UniversalClient,
	filter *keyfilter.Set,
	opts searchOptions,
	emit func(*types.ClientKeysSearchEvent) error,
) error {
	scanCount := opts.scanCount
	if scanCount <= 0 {
		scanCount = defaultScanCount
	}
	limit := opts.limit
	if limit <= 0 {
		limit = defaultSearchLimit
	}
	budget := opts.budget
	if budget <= 0 {
		budget = defaultSearchBudget
	}

	match := opts.match
	if match == "" {
		match = "*"
	}

	var (
		cursor    = opts.cursor
		deadline  = time.Now().Add(budget)
		batch     []string
		scanned   uint64
		matched   uint64
		lastEmit  = time.Now()
		truncated bool
	)

	send := func(done bool) error {
		err := emit(&types.ClientKeysSearchEvent{
			Keys:      batch,
			Scanned:   scanned,
			Matched:   matched,
			Cursor:    strconv.FormatUint(cursor, 10),
			Done:      done,
			Truncated: truncated,
		})
		batch = nil
		lastEmit = time.Now()
		return err
	}

	for {
		var (
			keys       []string
			nextCursor uint64
			err        error
		)
		roundCursor := cursor
		if opts.keyType != "" {
			keys, nextCursor, err = rdb.ScanType(ctx, cursor, match, scanCount, opts.keyType).Result()
		} else {
			keys, nextCursor, err = rdb.Scan(ctx, cursor, match, scanCount).Result()
		}
		if err != nil {
			return err
		}

		scanned += uint64(len(keys))
		for _, k := range keys {
			if !filter.Match(k) {
				continue
			}
			batch = append(batch, util.EncodeRedisKey(k).(string))
			matched++
			if matched >= uint64(limit) {
				truncated = true
				break
			}
		}

		if truncated {
			cursor = roundCursor
			return send(true)
		}

		cursor = nextCursor

		if cursor == 0 {
			return send(true)
		}

		if time.Now().After(deadline) {
			truncated = true
			return send(true)
		}

		if len(batch) >= searchEmitBatch || time.Since(lastEmit) >= searchProgressInterval {
			if err := send(false); err != nil {
				return err // client hung up
			}
		}

		if err := ctx.Err(); err != nil {
			return err
		}
	}
}

func parseSearchCursor(s string) (uint64, error) {
	if s == "" || s == "0" {
		return 0, nil
	}
	return strconv.ParseUint(s, 10, 64)
}
