// Code generated by scorix.
package client

import (
	"context"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeysMetadataLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeysMetadataLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeysMetadataLogic {
	return &KeysMetadataLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeysMetadataLogic) KeysMetadata(params *types.ClientKeysMetadataReq) (*types.ClientKeysMetadataRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	items := make([]types.KeyMetadata, 0)

	pipe := cli.Rdb.Pipeline()
	typeCmds := make(map[string]*redis.StatusCmd)
	ttlCmds := make(map[string]*redis.DurationCmd)
	sizeCmds := make(map[string]*redis.IntCmd)

	for _, key := range params.Keys {
		typeCmds[key] = pipe.Type(l.ctx, key)
		ttlCmds[key] = pipe.PTTL(l.ctx, key)
		sizeCmds[key] = pipe.MemoryUsage(l.ctx, key)
	}

	_, _ = pipe.Exec(l.ctx)

	for _, key := range params.Keys {
		item := types.KeyMetadata{
			Key:  key,
			Type: typeCmds[key].Val(),
			Ttl:  int64(ttlCmds[key].Val()),
			Size: sizeCmds[key].Val(),
		}
		items = append(items, item)
	}

	return &types.ClientKeysMetadataRes{
		Items: items,
	}, nil
}
