// Code generated by scorix.
package client

import (
	"context"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeysDeleteByPrefixLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeysDeleteByPrefixLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeysDeleteByPrefixLogic {
	return &KeysDeleteByPrefixLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeysDeleteByPrefixLogic) KeysDeleteByPrefix(params *types.ClientKeysDeleteByPrefixReq) (*types.ClientKeysDeleteByPrefixRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	eventTopic := fmt.Sprintf("client:keys-delete-progress:%s", params.ConnectionId)

	if len(params.Keys) > 0 {
		batchSize := 1000
		totalDeleted := 0
		for i := 0; i < len(params.Keys); i += batchSize {
			end := i + batchSize
			if end > len(params.Keys) {
				end = len(params.Keys)
			}
			batch := params.Keys[i:end]

			err = cli.Rdb.Del(l.ctx, batch...).Err()
			if err != nil {
				return nil, err
			}
			totalDeleted += len(batch)

			l.svcCtx.App.Evt().Emit(l.ctx, "", eventTopic, map[string]any{
				"prefix":  params.Prefix,
				"deleted": totalDeleted,
				"total":   len(params.Keys),
				"status":  "processing",
			})
		}

		l.svcCtx.App.Evt().Emit(l.ctx, "", eventTopic, map[string]any{
			"prefix":  params.Prefix,
			"deleted": totalDeleted,
			"total":   len(params.Keys),
			"status":  "done",
		})

		return &types.ClientKeysDeleteByPrefixRes{
			TotalDeleted: int32(totalDeleted),
		}, nil
	}

	if params.Prefix == "" {
		return nil, fmt.Errorf("prefix or keys must be provided")
	}

	match := params.Prefix + "*"
	cursor := uint64(0)
	batchSize := int64(1000)
	totalDeleted := 0

	for {
		keys, nextCursor, err := cli.Rdb.Scan(l.ctx, cursor, match, batchSize).Result()
		if err != nil {
			return nil, err
		}

		if len(keys) > 0 {
			err = cli.Rdb.Del(l.ctx, keys...).Err()
			if err != nil {
				return nil, err
			}
			totalDeleted += len(keys)

			l.svcCtx.App.Evt().Emit(l.ctx, "", eventTopic, map[string]any{
				"prefix":  params.Prefix,
				"deleted": totalDeleted,
				"status":  "processing",
			})
		}

		cursor = nextCursor
		if cursor == 0 {
			break
		}
	}

	l.svcCtx.App.Evt().Emit(l.ctx, "", eventTopic, map[string]any{
		"prefix":  params.Prefix,
		"deleted": totalDeleted,
		"status":  "done",
	})

	return &types.ClientKeysDeleteByPrefixRes{
		TotalDeleted: int32(totalDeleted),
	}, nil
}
