// Code generated by scorix.
package client

import (
	"context"
	"strconv"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type LoadAllKeysLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLoadAllKeysLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LoadAllKeysLogic {
	return &LoadAllKeysLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *LoadAllKeysLogic) LoadAllKeys(params *types.ClientLoadAllKeysReq) (*types.ClientLoadAllKeysRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	pattern := params.Prefix
	if !strings.Contains(pattern, "*") {
		pattern += "*"
	}

	cursor, _ := strconv.ParseUint(params.Cursor, 10, 64)
	keys, nextCursor, err := cli.Rdb.Scan(l.ctx, cursor, pattern, params.Count).Result()
	if err != nil {
		return nil, err
	}

	return &types.ClientLoadAllKeysRes{
		Keys:   keys,
		Cursor: strconv.FormatUint(nextCursor, 10),
	}, nil
}
