// Code generated by scorix.
package client

import (
	"context"
	"fmt"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/util"
)

type LoadKeyDetailLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLoadKeyDetailLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LoadKeyDetailLogic {
	return &LoadKeyDetailLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *LoadKeyDetailLogic) LoadKeyDetail(params *types.ClientLoadKeyDetailReq) (*types.ClientLoadKeyDetailRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	var valueStr string
	var kind string
	var total int64
	var key = params.Key

	kind, err = cli.Rdb.Type(l.ctx, key).Result()
	if err != nil {
		return nil, err
	}
	if kind == "none" {
		return nil, fmt.Errorf("key not exists")
	}

	ttl, err := cli.Rdb.TTL(l.ctx, key).Result()
	if err != nil {
		return nil, err
	}

	var ttlSec float64
	switch ttl {
	case -1, -2:
		ttlSec = float64(ttl)
	default:
		ttlSec = ttl.Seconds()
	}

	switch strings.ToLower(kind) {
	case "string":
		var str string
		str, err = cli.Rdb.Get(l.ctx, key).Result()
		valueStr = util.EncodeRedisKey(str).(string)
	case "list":
		total, err = cli.Rdb.LLen(l.ctx, key).Result()
	case "hash":
		total, err = cli.Rdb.HLen(l.ctx, key).Result()
	case "set":
		total, err = cli.Rdb.SCard(l.ctx, key).Result()
	case "zset":
		total, err = cli.Rdb.ZCard(l.ctx, key).Result()
	case "stream":
		total, err = cli.Rdb.XLen(l.ctx, key).Result()
	case "rejson-rl":
		val, _ := cli.Rdb.JSONGet(l.ctx, key).Result()
		valueStr = val
	case "json", "rejson":
		// handled as string by the client
	}

	if err != nil {
		return nil, err
	}

	return &types.ClientLoadKeyDetailRes{
		Key:   key,
		Value: valueStr,
		Kind:  strings.ToLower(kind),
		Ttl:   ttlSec,
		Total: total,
	}, nil
}
