// Code generated by scorix.
package client

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type LoadKeyValuePageLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLoadKeyValuePageLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LoadKeyValuePageLogic {
	return &LoadKeyValuePageLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

type HashPageItem struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

type ListPageItem struct {
	Index int64  `json:"index"`
	Value string `json:"value"`
}

type SetPageItem struct {
	Member string `json:"member"`
}

type ZSetPageItem struct {
	Member string  `json:"member"`
	Score  float64 `json:"score"`
}

type StreamPageItem struct {
	Id    string                 `json:"id"`
	Value map[string]interface{} `json:"value"`
}

func (l *LoadKeyValuePageLogic) LoadKeyValuePage(params *types.ClientLoadKeyValuePageReq) (*types.ClientLoadKeyValuePageRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	pageSize := params.PageSize
	if pageSize <= 0 {
		pageSize = 200
	}

	cursor := params.Cursor
	if cursor == "" {
		cursor = "0"
	}

	res := &types.ClientLoadKeyValuePageRes{
		Items: make([]types.KeyValuePageItem, 0),
	}

	switch strings.ToLower(params.Kind) {
	case "hash":
		cursorInt, _ := strconv.ParseUint(cursor, 10, 64)
		keys, nextCursor, err := cli.Rdb.HScan(l.ctx, params.Key, cursorInt, "*", pageSize).Result()
		if err != nil {
			return nil, err
		}
		for i := 0; i+1 < len(keys); i += 2 {
			res.Items = append(res.Items, types.KeyValuePageItem{Field: keys[i], Value: keys[i+1]})
		}
		res.NextCursor = strconv.FormatUint(nextCursor, 10)
		res.HasMore = nextCursor != 0

	case "set":
		cursorInt, _ := strconv.ParseUint(cursor, 10, 64)
		members, nextCursor, err := cli.Rdb.SScan(l.ctx, params.Key, cursorInt, "*", pageSize).Result()
		if err != nil {
			return nil, err
		}
		for _, m := range members {
			res.Items = append(res.Items, types.KeyValuePageItem{Member: m})
		}
		res.NextCursor = strconv.FormatUint(nextCursor, 10)
		res.HasMore = nextCursor != 0

	case "zset":
		cursorInt, _ := strconv.ParseUint(cursor, 10, 64)
		vals, nextCursor, err := cli.Rdb.ZScan(l.ctx, params.Key, cursorInt, "*", pageSize).Result()
		if err != nil {
			return nil, err
		}
		for i := 0; i+1 < len(vals); i += 2 {
			score, _ := strconv.ParseFloat(vals[i+1], 64)
			res.Items = append(res.Items, types.KeyValuePageItem{Member: vals[i], Score: score})
		}
		res.NextCursor = strconv.FormatUint(nextCursor, 10)
		res.HasMore = nextCursor != 0

	case "list":
		offset, _ := strconv.ParseInt(cursor, 10, 64)
		totalLen, err := cli.Rdb.LLen(l.ctx, params.Key).Result()
		if err != nil {
			return nil, err
		}
		vals, err := cli.Rdb.LRange(l.ctx, params.Key, offset, offset+pageSize-1).Result()
		if err != nil {
			return nil, err
		}
		for i, v := range vals {
			res.Items = append(res.Items, types.KeyValuePageItem{Index: offset + int64(i), Value: v})
		}
		nextOffset := offset + int64(len(vals))
		res.HasMore = nextOffset < totalLen
		res.NextCursor = strconv.FormatInt(nextOffset, 10)
		if !res.HasMore {
			res.NextCursor = "0"
		}

	case "stream":
		start := cursor
		if start == "0" || start == "" {
			start = "-"
		} else {
			start = incrementStreamID(start)
		}
		msgs, err := cli.Rdb.XRangeN(l.ctx, params.Key, start, "+", pageSize).Result()
		if err != nil {
			return nil, err
		}
		for _, msg := range msgs {
			res.Items = append(res.Items, types.KeyValuePageItem{Id: msg.ID, Value: fmt.Sprintf("%v", msg.Values)})
		}
		res.HasMore = int64(len(msgs)) >= pageSize
		res.NextCursor = "0"
		if res.HasMore && len(msgs) > 0 {
			res.NextCursor = msgs[len(msgs)-1].ID
		}

	default:
		return nil, fmt.Errorf("unsupported kind: %s", params.Kind)
	}

	return res, nil
}

func incrementStreamID(id string) string {
	parts := strings.SplitN(id, "-", 2)
	if len(parts) != 2 {
		return id
	}
	seq, err := strconv.ParseUint(parts[1], 10, 64)
	if err != nil {
		return id
	}
	return fmt.Sprintf("%s-%d", parts[0], seq+1)
}
