// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ProbeLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewProbeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ProbeLogic {
	return &ProbeLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}
func (l *ProbeLogic) Probe(params *types.ClientProbeReq) (*types.Empty, error) {
	if err := l.svcCtx.RedisManager.Probe(l.ctx, params.ConnectionId); err != nil {
		return nil, err
	}
	return &types.Empty{}, nil
}
