// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type SearchKeysLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSearchKeysLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SearchKeysLogic {
	return &SearchKeysLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *SearchKeysLogic) SearchKeys(params *types.ClientSearchKeysReq) (*types.ClientSearchKeysRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	count := params.Count
	if count <= 0 {
		count = 50
	}

	match := params.Prefix + "*"

	keys, _, err := cli.Rdb.Scan(l.ctx, 0, match, count).Result()
	if err != nil {
		return nil, err
	}

	return &types.ClientSearchKeysRes{
		Keys: keys,
	}, nil
}
