// Code generated by scorix.
package client

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type SetReadOnlyLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSetReadOnlyLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SetReadOnlyLogic {
	return &SetReadOnlyLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *SetReadOnlyLogic) SetReadOnly(params *types.ClientSetReadOnlyReq) (*types.Empty, error) {
	conn, err := l.svcCtx.ConnectionModel.FindOne(l.ctx, params.ConnectionId)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("connection not found: %s", params.ConnectionId)
		}
		return nil, err
	}

	want := int64(0)
	if params.ReadOnly {
		want = 1
	}
	if conn.ReadOnly != want {
		conn.ReadOnly = want
		if err := l.svcCtx.ConnectionModel.Update(l.ctx, conn); err != nil {
			return nil, err
		}
	}

	l.svcCtx.RedisManager.SetReadOnly(params.ConnectionId, params.ReadOnly)
	return &types.Empty{}, nil
}
