// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type StatesLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewStatesLogic(ctx context.Context, svcCtx *svc.ServiceContext) *StatesLogic {
	return &StatesLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}
func (l *StatesLogic) States(params *types.Empty) (*types.ClientStatesRes, error) {
	return &types.ClientStatesRes{Items: l.svcCtx.RedisManager.States()}, nil
}
