app:
  name: RedisHub
  version: 1.8.0
  identifier: com.tradalab.redishub
  description: "RedisHub"
  authors: [ "TradaLab Team" ]
  license: "UNLICENSE"
  icon: "assets/icon.ico"

window:
  title: RedisHub
  width: 1024
  height: 768
  debug: false

security:
  csp: none
  allow_right_click: false
  allowlist:
    fs: true
    shell: true
    http: true
    clipboard: true
    notification: true

logger:
  level: debug
  format: console        # console, json
  output: stdout      # stdout, file, both
  file: logs/app.log
  max_size: 10        # MB
  max_age: 7          # days

modules:
  browser:
    enabled: true
  gorm:
    enabled: true
    driver: sqlite
    dsn: "app.dat"
  updater:
    enabled: true
    provider: github
    github_repo: tradalab/redishub
    appcast_url: https://cdn.tradalab.com/redishub/appcast.json
    public_key_base_64:
    platform_key:
    force_elevate: true
    current_version: 1.8.0
