// Code generated by scorix. DO NOT EDIT.
package etc

import _ "embed"

// SchemaSQL holds the embedded contents of schema.sql. Pass to
// scorixsqlx.WithSchema so the sqlx module installs it during OnLoad.
// Script must be idempotent (CREATE TABLE/INDEX IF NOT EXISTS).
//
//go:embed schema.sql
var SchemaSQL string
