FROM ubuntu:20.04 AS base

ENV DEBIAN_FRONTEND=noninteractive
ENV GO_VERSION=1.24.10

# install deps
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    wget \
    git \
    build-essential \
    pkg-config \
    fuse \
    file \
    patchelf \
    squashfs-tools \
    xz-utils \
    libgtk-3-dev \
    libwebkit2gtk-4.0-dev \
    && rm -rf /var/lib/apt/lists/*

# install go
RUN wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
    rm go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

# install linuxdeploy
RUN wget -q -O linuxdeploy \
    https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage && \
    mv linuxdeploy /usr/local/bin/linuxdeploy && \
    chmod 755 /usr/local/bin/linuxdeploy
