// Code generated by scorix.
package setting

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type GetLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewGetLogic(ctx context.Context, svcCtx *svc.ServiceContext) *GetLogic {
	return &GetLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *GetLogic) Get(params *types.SettingGetReq) (*types.SettingItem, error) {
	s, err := l.svcCtx.SettingModel.FindOneByKey(l.ctx, params.Key)
	if err != nil {
		return nil, err
	}
	return &types.SettingItem{
		Key:   s.Key,
		Value: s.Value,
	}, nil
}
