// Code generated by scorix.
package setting

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.SettingListRes, error) {
	settings, err := l.svcCtx.SettingModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	var items []types.SettingItem
	for _, s := range settings {
		items = append(items, types.SettingItem{
			Key:   s.Key,
			Value: s.Value,
		})
	}

	return &types.SettingListRes{
		Items: items,
	}, nil
}
