// Code generated by scorix.
package setting

import (
	"context"
	"database/sql"
	"errors"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type SetLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSetLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SetLogic {
	return &SetLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *SetLogic) Set(params *types.SettingSetReq) (*types.Empty, error) {
	existing, err := l.svcCtx.SettingModel.FindOneByKey(l.ctx, params.Key)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, err
	}

	if errors.Is(err, sql.ErrNoRows) {
		s := &model.Setting{
			Key:   params.Key,
			Value: params.Value,
		}
		if _, err := l.svcCtx.SettingModel.Insert(l.ctx, s); err != nil {
			return nil, err
		}
		return &types.Empty{}, nil
	}

	existing.Value = params.Value
	if err := l.svcCtx.SettingModel.Update(l.ctx, existing); err != nil {
		return nil, err
	}
	return &types.Empty{}, nil
}
