// Code generated by scorix.
package svc

import (
	"context"
	"encoding/json"

	"github.com/tradalab/rdms/internal/config"
	// scorix:model:imports:start
	"github.com/jmoiron/sqlx"
	"github.com/tradalab/rdms/etc"
	"github.com/tradalab/rdms/internal/model"
	scorixsqlx "github.com/tradalab/scorix/module/sqlx"
	_ "modernc.org/sqlite"

	// scorix:model:imports:end
	"github.com/tradalab/scorix/app"
)

type ServiceContext struct {
	Cfg          *config.Config
	RedisManager *ClientManager
	sqlx         *scorixsqlx.Module
	// scorix:model:fields:start
	ConnectionModel model.ConnectionModel
	SshModel        model.SshModel
	TlsModel        model.TlsModel
	ProxyModel      model.ProxyModel
	GroupModel      model.GroupModel
	SettingModel    model.SettingModel
	// scorix:model:fields:end

	emit   func(name string, data any)
	emitTo func(client app.ClientID, name string, data any) bool
	on     func(name string, fn func(context.Context, json.RawMessage))
}

func NewServiceContext(a *app.App) *ServiceContext {
	initSecretCodec()
	// scorix:model:init:start
	sqlxMod := scorixsqlx.New(scorixsqlx.WithSchema(etc.SchemaSQL))
	sqlxMod.RegisterDriver("sqlite", func(dsn string) (*sqlx.DB, error) { return sqlx.Connect("sqlite", dsn) })
	a.Module(sqlxMod)
	// scorix:model:init:end
	return &ServiceContext{
		Cfg:          &config.Config{},
		RedisManager: NewManager(),
		sqlx:         sqlxMod,
		// scorix:model:assigns:start
		ConnectionModel: model.NewConnectionModel(sqlxMod.Conn),
		SshModel:        model.NewSshModel(sqlxMod.Conn),
		TlsModel:        model.NewTlsModel(sqlxMod.Conn),
		ProxyModel:      model.NewProxyModel(sqlxMod.Conn),
		GroupModel:      model.NewGroupModel(sqlxMod.Conn),
		SettingModel:    model.NewSettingModel(sqlxMod.Conn),
		// scorix:model:assigns:end
		emit:   a.Emit,
		emitTo: a.EmitTo,
		on:     func(name string, fn func(context.Context, json.RawMessage)) { a.Event(name, fn) },
	}
}

func (s *ServiceContext) Emit(name string, data any) {
	if s.emit != nil {
		s.emit(name, data)
	}
}

func (s *ServiceContext) EmitTo(client app.ClientID, name string, data any) bool {
	if s.emitTo != nil {
		return s.emitTo(client, name, data)
	}
	return false
}

func (s *ServiceContext) On(name string, fn func(context.Context, json.RawMessage)) {
	if s.on != nil {
		s.on(name, fn)
	}
}
