// Code generated by scorix.
package proxy

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type DeleteLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewDeleteLogic(ctx context.Context, svcCtx *svc.ServiceContext) *DeleteLogic {
	return &DeleteLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *DeleteLogic) Delete(params *types.IdReq) (*types.Empty, error) {
	if err := l.svcCtx.ProxyModel.Delete(l.ctx, params.Id); err != nil {
		return nil, err
	}
	return &types.Empty{}, nil
}
