// Code generated by scorix.
package proxy

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.ProxyListRes, error) {
	proxies, err := l.svcCtx.ProxyModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	var items []types.ProxyReq
	for _, p := range proxies {
		items = append(items, types.ProxyReq{
			Id:       p.ID,
			Protocol: p.Protocol,
			Host:     p.Host,
			Port:     int32(p.Port),
			Username: p.Username,
			Password: "", // secrets are never sent to the client
		})
	}

	return &types.ProxyListRes{
		Items: items,
	}, nil
}
