// Code generated by scorix.
package proxy

import (
	"context"
	"database/sql"
	"errors"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type UpsertLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpsertLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpsertLogic {
	return &UpsertLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UpsertLogic) Upsert(params *types.ProxyReq) (*types.UpsertRes, error) {
	var p *model.Proxy
	if params.Id != "" {
		existing, err := l.svcCtx.ProxyModel.FindOne(l.ctx, params.Id)
		if err == nil {
			p = existing
		} else if !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
	}

	isNew := p == nil
	if isNew {
		p = &model.Proxy{
			ID: params.Id,
		}
	}

	p.Protocol = params.Protocol
	p.Host = params.Host
	p.Port = int64(params.Port)
	p.Username = params.Username
	p.Password = params.Password

	if isNew {
		if _, err := l.svcCtx.ProxyModel.Insert(l.ctx, p); err != nil {
			return nil, err
		}
	} else {
		if err := l.svcCtx.ProxyModel.Update(l.ctx, p); err != nil {
			return nil, err
		}
	}

	return &types.UpsertRes{Id: p.ID}, nil
}
