// Code generated by scorix.
package pubsub

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type PublishLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewPublishLogic(ctx context.Context, svcCtx *svc.ServiceContext) *PublishLogic {
	return &PublishLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *PublishLogic) Publish(params *types.PubSubPublishReq) (*types.Empty, error) {
	c, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	_, err = c.Rdb.Publish(l.ctx, params.Channel, params.Message).Result()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
