// Code generated by scorix.
package pubsub

import (
	"context"
	"fmt"

	"github.com/tradalab/scorix/app"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type StreamLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewStreamLogic(ctx context.Context, svcCtx *svc.ServiceContext) *StreamLogic {
	return &StreamLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *StreamLogic) Stream(req *types.PubSubStreamReq, out app.Sink[types.PubsubMessageEvent]) error {
	c, err := l.svcCtx.RedisManager.Get(req.ConnectionId, int(req.DatabaseIndex))
	if err != nil {
		return err
	}

	c.PubSubMu.Lock()
	if c.PubSubActive {
		c.PubSubMu.Unlock()
		return fmt.Errorf("pubsub stream already open for this connection")
	}
	if c.PubSub == nil {
		c.PubSub = c.Rdb.Subscribe(context.Background())
	}
	c.PubSubActive = true
	ch := c.PubSub.Channel()
	c.PubSubMu.Unlock()

	defer func() {
		c.PubSubMu.Lock()
		c.PubSubActive = false
		if c.PubSub != nil {
			_ = c.PubSub.Close()
			c.PubSub = nil
		}
		c.PubSubMu.Unlock()
	}()

	for {
		select {
		case <-out.Context().Done():
			return nil
		case msg, ok := <-ch:
			if !ok {
				return nil
			}
			if err := out.Send(&types.PubsubMessageEvent{
				ConnectionId: req.ConnectionId,
				Channel:      msg.Channel,
				Message:      msg.Payload,
				Pattern:      msg.Pattern,
			}); err != nil {
				return err
			}
		}
	}
}
