// Code generated by scorix.
package pubsub

import (
	"context"
	"fmt"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type SubscribeLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSubscribeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SubscribeLogic {
	return &SubscribeLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

type PubsubMessage struct {
	Channel string `json:"channel"`
	Message string `json:"message"`
	Pattern string `json:"pattern,omitempty"`
}

func (l *SubscribeLogic) Subscribe(params *types.PubSubSubscribeReq) (*types.Empty, error) {
	c, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	c.PubSubMu.Lock()
	defer c.PubSubMu.Unlock()

	if c.PubSub == nil {
		c.PubSub = c.Rdb.Subscribe(context.Background())
	}

	var exact []string
	var pattern []string

	for _, ch := range params.Channels {
		if strings.ContainsAny(ch, "*?") {
			pattern = append(pattern, ch)
		} else {
			exact = append(exact, ch)
		}
	}

	if len(exact) > 0 {
		err = c.PubSub.Subscribe(l.ctx, exact...)
		if err != nil {
			return nil, err
		}
	}
	if len(pattern) > 0 {
		err = c.PubSub.PSubscribe(l.ctx, pattern...)
		if err != nil {
			return nil, err
		}
	}

	if !c.PubSubActive {
		c.PubSubActive = true
		eventOut := fmt.Sprintf("pubsub:message:%s", params.ConnectionId)

		go func() {
			defer func() {
				c.PubSubMu.Lock()
				c.PubSubActive = false
				c.PubSubMu.Unlock()
			}()

			ch := c.PubSub.Channel()
			for msg := range ch {
				l.svcCtx.App.Evt().Emit(context.Background(), "", eventOut, PubsubMessage{
					Channel: msg.Channel,
					Message: msg.Payload,
					Pattern: msg.Pattern,
				})
			}
		}()
	}

	return &types.Empty{}, nil
}
