// Code generated by scorix.
package pubsub

import (
	"context"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type UnsubscribeLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUnsubscribeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UnsubscribeLogic {
	return &UnsubscribeLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UnsubscribeLogic) Unsubscribe(params *types.PubSubSubscribeReq) (*types.Empty, error) {
	c, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	c.PubSubMu.Lock()
	defer c.PubSubMu.Unlock()

	if c.PubSub != nil {
		if len(params.Channels) == 0 {
			err = c.PubSub.Unsubscribe(context.Background())
			_ = c.PubSub.PUnsubscribe(context.Background())
		} else {
			var exact []string
			var pattern []string

			for _, ch := range params.Channels {
				if strings.ContainsAny(ch, "*?") {
					pattern = append(pattern, ch)
				} else {
					exact = append(exact, ch)
				}
			}

			if len(exact) > 0 {
				err = c.PubSub.Unsubscribe(context.Background(), exact...)
			}
			if len(pattern) > 0 {
				errPattern := c.PubSub.PUnsubscribe(context.Background(), pattern...)
				if err == nil {
					err = errPattern
				}
			}
		}

		if err != nil {
			return nil, err
		}
	}

	return &types.Empty{}, nil
}
