// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type HashFieldDelLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewHashFieldDelLogic(ctx context.Context, svcCtx *svc.ServiceContext) *HashFieldDelLogic {
	return &HashFieldDelLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *HashFieldDelLogic) HashFieldDel(params *types.KeyHashFieldDelReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "hash" {
		return nil, fmt.Errorf("key type mismatch: expected hash, got %s", keyType)
	}

	_, err = cli.Rdb.HDel(l.ctx, params.Key, params.Field).Result()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
