// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type HashFieldUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewHashFieldUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *HashFieldUpdateLogic {
	return &HashFieldUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *HashFieldUpdateLogic) HashFieldUpdate(params *types.KeyHashFieldUpdateReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}
	if params.Field == "" {
		return nil, errors.New("field is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "hash" {
		return nil, fmt.Errorf("key type mismatch: expected hash, got %s", keyType)
	}

	if params.NewField == "" || params.NewField == params.Field {
		if err := cli.Rdb.HSet(l.ctx, params.Key, params.Field, params.Value).Err(); err != nil {
			return nil, err
		}
		return &types.Empty{}, nil
	}

	exists, err := cli.Rdb.HExists(l.ctx, params.Key, params.NewField).Result()
	if err != nil {
		return nil, err
	}
	if exists {
		return nil, errors.New("field already exists")
	}
	if err := cli.Rdb.HSet(l.ctx, params.Key, params.NewField, params.Value).Err(); err != nil {
		return nil, err
	}
	if err := cli.Rdb.HDel(l.ctx, params.Key, params.Field).Err(); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
