// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListItemUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListItemUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListItemUpdateLogic {
	return &ListItemUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListItemUpdateLogic) ListItemUpdate(params *types.KeyListItemUpdateReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "list" {
		return nil, fmt.Errorf("key type mismatch: expected list, got %s", keyType)
	}

	length, err := cli.Rdb.LLen(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if params.Index < 0 || params.Index >= length {
		return nil, fmt.Errorf("item index out of range")
	}

	currentValue, err := cli.Rdb.LIndex(l.ctx, params.Key, params.Index).Result()
	if err != nil {
		return nil, err
	}
	if currentValue != params.OldValue {
		return nil, errors.New("list item changed, please reload")
	}

	if err := cli.Rdb.LSet(l.ctx, params.Key, params.Index, params.Value).Err(); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
