// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListItemDelLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListItemDelLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListItemDelLogic {
	return &ListItemDelLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListItemDelLogic) ListItemDel(params *types.KeyListItemDelReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "list" {
		return nil, fmt.Errorf("key type mismatch: expected list, got %s", keyType)
	}

	length, err := cli.Rdb.LLen(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if params.Index < 0 || params.Index >= length {
		return nil, fmt.Errorf("item index out of range")
	}

	currentValue, err := cli.Rdb.LIndex(l.ctx, params.Key, params.Index).Result()
	if err != nil {
		return nil, err
	}
	if currentValue != params.Value {
		return nil, errors.New("list item changed, please reload")
	}

	deleteMarker := fmt.Sprintf("__deleted__:%d", time.Now().UnixNano())

	if err := cli.Rdb.LSet(l.ctx, params.Key, params.Index, deleteMarker).Err(); err != nil {
		return nil, err
	}

	_, err = cli.Rdb.LRem(l.ctx, params.Key, 1, deleteMarker).Result()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
