// Code generated by scorix.
package key

import (
	"context"
	"strconv"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/util"
)

type LoadLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLoadLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LoadLogic {
	return &LoadLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *LoadLogic) Load(params *types.KeyLoadReq) (*types.KeyLoadRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	cursorStr := params.Cursor
	if cursorStr == "" {
		cursorStr = "0"
	}

	num, err := strconv.ParseUint(cursorStr, 10, 64)
	if err != nil {
		return nil, err
	}

	count := params.Count
	if count <= 0 {
		count = 1000
	}

	keys, nextCursor, err := scanKeys(l.ctx, cli.Rdb, "", "", num, count)
	if err != nil {
		return nil, err
	}

	return &types.KeyLoadRes{
		Keys:   keys,
		Cursor: strconv.FormatUint(nextCursor, 10),
	}, nil
}

func scanKeys(ctx context.Context, client redis.UniversalClient, match, keyType string, cursor uint64, count int64) ([]string, uint64, error) {
	var err error
	filterType := len(keyType) > 0

	scanSize := count
	if scanSize <= 0 {
		scanSize = 500
	}

	var keys []string
	var loadedKey []string

	if filterType {
		loadedKey, cursor, err = client.ScanType(ctx, cursor, match, scanSize, keyType).Result()
	} else {
		loadedKey, cursor, err = client.Scan(ctx, cursor, match, scanSize).Result()
	}
	if err != nil {
		return nil, cursor, err
	}

	for _, v := range loadedKey {
		keys = append(keys, util.EncodeRedisKey(v).(string))
	}

	return keys, cursor, nil
}
