// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type SetMemberUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSetMemberUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SetMemberUpdateLogic {
	return &SetMemberUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *SetMemberUpdateLogic) SetMemberUpdate(params *types.KeySetMemberUpdateReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}
	if params.Member == "" {
		return nil, errors.New("member is required")
	}
	if params.NewMember == "" {
		return nil, errors.New("new member is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "set" {
		return nil, fmt.Errorf("key type mismatch: expected set, got %s", keyType)
	}

	if params.NewMember == params.Member {
		return &types.Empty{}, nil
	}

	stillThere, err := cli.Rdb.SIsMember(l.ctx, params.Key, params.Member).Result()
	if err != nil {
		return nil, err
	}
	if !stillThere {
		return nil, errors.New("member changed, please reload")
	}

	exists, err := cli.Rdb.SIsMember(l.ctx, params.Key, params.NewMember).Result()
	if err != nil {
		return nil, err
	}
	if exists {
		return nil, errors.New("member already exists")
	}
	if err := cli.Rdb.SAdd(l.ctx, params.Key, params.NewMember).Err(); err != nil {
		return nil, err
	}
	if err := cli.Rdb.SRem(l.ctx, params.Key, params.Member).Err(); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
