// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type StreamEntryDelLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewStreamEntryDelLogic(ctx context.Context, svcCtx *svc.ServiceContext) *StreamEntryDelLogic {
	return &StreamEntryDelLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *StreamEntryDelLogic) StreamEntryDel(params *types.KeyStreamEntryDelReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}
	if params.EntryId == "" {
		return nil, errors.New("entry_id is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "stream" {
		return nil, fmt.Errorf("key type mismatch: expected stream, got %s", keyType)
	}

	_, err = cli.Rdb.XDel(l.ctx, params.Key, params.EntryId).Result()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
