// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ZSetMemberUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewZSetMemberUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ZSetMemberUpdateLogic {
	return &ZSetMemberUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ZSetMemberUpdateLogic) ZSetMemberUpdate(params *types.KeyZSetMemberUpdateReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}
	if params.Member == "" {
		return nil, errors.New("member is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "zset" {
		return nil, fmt.Errorf("key type mismatch: expected zset, got %s", keyType)
	}

	if params.NewMember == "" || params.NewMember == params.Member {
		if err := cli.Rdb.ZAdd(l.ctx, params.Key, redis.Z{Member: params.Member, Score: params.Score}).Err(); err != nil {
			return nil, err
		}
		return &types.Empty{}, nil
	}

	_, err = cli.Rdb.ZScore(l.ctx, params.Key, params.NewMember).Result()
	if err == nil {
		return nil, errors.New("member already exists")
	}
	if err != redis.Nil {
		return nil, err
	}
	if err := cli.Rdb.ZAdd(l.ctx, params.Key, redis.Z{Member: params.NewMember, Score: params.Score}).Err(); err != nil {
		return nil, err
	}
	if err := cli.Rdb.ZRem(l.ctx, params.Key, params.Member).Err(); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
