// Code generated by scorix.
package key

import (
	"context"
	"errors"
	"fmt"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ZSetMemberDelLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewZSetMemberDelLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ZSetMemberDelLogic {
	return &ZSetMemberDelLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ZSetMemberDelLogic) ZSetMemberDel(params *types.KeyZSetMemberDelReq) (*types.Empty, error) {
	if params.Key == "" {
		return nil, errors.New("key is required")
	}
	if params.Member == "" {
		return nil, errors.New("member is required")
	}

	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	keyType, err := cli.Rdb.Type(l.ctx, params.Key).Result()
	if err != nil {
		return nil, err
	}
	if keyType != "zset" {
		return nil, fmt.Errorf("key type mismatch: expected zset, got %s", keyType)
	}

	_, err = cli.Rdb.ZRem(l.ctx, params.Key, params.Member).Result()
	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
