// Code generated by scorix.
package tls

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.TlsListRes, error) {
	tlss, err := l.svcCtx.TlsModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	var items []types.TlsReq
	for _, t := range tlss {
		items = append(items, types.TlsReq{
			Id:         t.ID,
			Name:       t.Name,
			UseSni:     t.UseSni > 0,
			ServerName: t.ServerName,
			Verify:     t.Verify > 0,
			ClientAuth: t.ClientAuth > 0,
			CaCert:     t.CaCert,
			Cert:       t.Cert,
			Key:        t.Key,
		})
	}

	return &types.TlsListRes{
		Items: items,
	}, nil
}
