// Code generated by scorix.
package tls

import (
	"context"
	"database/sql"
	"errors"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type UpsertLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpsertLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpsertLogic {
	return &UpsertLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UpsertLogic) Upsert(params *types.TlsReq) (*types.UpsertRes, error) {
	var t *model.Tls
	if params.Id != "" {
		existing, err := l.svcCtx.TlsModel.FindOne(l.ctx, params.Id)
		if err == nil {
			t = existing
		} else if !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
	}

	isNew := t == nil
	if isNew {
		t = &model.Tls{
			ID: params.Id,
		}
	}

	t.Name = params.Name
	t.UseSni = bToI(params.UseSni)
	t.ServerName = params.ServerName
	t.Verify = bToI(params.Verify)
	t.ClientAuth = bToI(params.ClientAuth)
	t.CaCert = params.CaCert
	t.Cert = params.Cert

	if isNew || params.Key != "" {
		t.Key = params.Key
	}

	if isNew {
		if _, err := l.svcCtx.TlsModel.Insert(l.ctx, t); err != nil {
			return nil, err
		}
	} else {
		if err := l.svcCtx.TlsModel.Update(l.ctx, t); err != nil {
			return nil, err
		}
	}

	return &types.UpsertRes{Id: t.ID}, nil
}

func bToI(b bool) int64 {
	if b {
		return 1
	}
	return 0
}
