// Code generated by scorix.
package connection

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.ConnectionListRes, error) {
	conns, err := l.svcCtx.ConnectionModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	var items []types.ConnectionReq
	for _, c := range conns {
		items = append(items, types.ConnectionReq{
			Id:               c.ID,
			Mode:             c.Mode,
			Name:             c.Name,
			Network:          c.Network,
			Host:             c.Host,
			Port:             int32(c.Port),
			Addrs:            c.Addrs,
			SentinelMaster:   c.SentinelMaster,
			SentinelUsername: c.SentinelUsername,
			SentinelPassword: "",
			Sock:             c.Sock,
			Username:         c.Username,
			Password:         "",
			AddrMapping:      c.AddrMapping,
			LastDb:           int32(c.LastDb),
			ExecTimeout:      c.ExecTimeout,
			DialTimeout:      c.DialTimeout,
			KeySize:          c.KeySize,
			GroupId:          c.GroupID,
			SshEnable:        c.SshEnable > 0,
			SshId:            c.SshID,
			ProxyEnable:      c.ProxyEnable > 0,
			ProxyId:          c.ProxyID,
			TlsEnable:        c.TlsEnable > 0,
			TlsId:            c.TlsID,
		})
	}

	return &types.ConnectionListRes{
		Items: items,
	}, nil
}
