// Code generated by scorix.
package connection

import (
	"context"
	"database/sql"
	"errors"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type UpsertLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpsertLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpsertLogic {
	return &UpsertLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UpsertLogic) Upsert(params *types.ConnectionReq) (*types.UpsertRes, error) {
	var c *model.Connection
	if params.Id != "" {
		existing, err := l.svcCtx.ConnectionModel.FindOne(l.ctx, params.Id)
		if err == nil {
			c = existing
		} else if !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
	}

	isNew := c == nil
	if isNew {
		c = &model.Connection{
			ID: params.Id,
		}
	}

	c.Mode = params.Mode
	c.Name = params.Name
	c.Network = params.Network
	c.Host = params.Host
	c.Port = int64(params.Port)
	c.Addrs = params.Addrs
	c.SentinelMaster = params.SentinelMaster
	c.SentinelUsername = params.SentinelUsername
	c.Sock = params.Sock
	c.Username = params.Username
	c.AddrMapping = params.AddrMapping
	c.LastDb = int64(params.LastDb)
	c.ExecTimeout = params.ExecTimeout
	c.DialTimeout = params.DialTimeout
	c.KeySize = params.KeySize
	c.GroupID = params.GroupId
	c.SshEnable = bToI(params.SshEnable)
	c.SshID = params.SshId
	c.ProxyEnable = bToI(params.ProxyEnable)
	c.ProxyID = params.ProxyId
	c.TlsEnable = bToI(params.TlsEnable)
	c.TlsID = params.TlsId
	c.ReadOnly = bToI(params.ReadOnly)

	if isNew || params.Password != "" {
		c.Password = params.Password
	}
	if isNew || params.SentinelPassword != "" {
		c.SentinelPassword = params.SentinelPassword
	}

	if isNew {
		if _, err := l.svcCtx.ConnectionModel.Insert(l.ctx, c); err != nil {
			return nil, err
		}
	} else {
		if err := l.svcCtx.ConnectionModel.Update(l.ctx, c); err != nil {
			return nil, err
		}
		l.svcCtx.RedisManager.SetReadOnly(c.ID, params.ReadOnly)
	}

	return &types.UpsertRes{Id: c.ID}, nil
}

func bToI(b bool) int64 {
	if b {
		return 1
	}
	return 0
}
