// Code generated by scorix.
package conn

import (
	"context"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type TestLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewTestLogic(ctx context.Context, svcCtx *svc.ServiceContext) *TestLogic {
	return &TestLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *TestLogic) Test(params *types.ConnectionReq) (*types.Empty, error) {
	conn := model.Connection{
		Mode:             params.Mode,
		Name:             params.Name,
		Network:          params.Network,
		Host:             params.Host,
		Port:             int64(params.Port),
		Addrs:            params.Addrs,
		SentinelMaster:   params.SentinelMaster,
		SentinelUsername: params.SentinelUsername,
		SentinelPassword: params.SentinelPassword,
		Sock:             params.Sock,
		Username:         params.Username,
		Password:         params.Password,
		AddrMapping:      params.AddrMapping,
		ExecTimeout:      params.ExecTimeout,
		DialTimeout:      params.DialTimeout,
		KeySize:          params.KeySize,
		SshEnable:        bToI(params.SshEnable),
		ProxyEnable:      bToI(params.ProxyEnable),
		TlsEnable:        bToI(params.TlsEnable),
	}

	var sshCfg *model.Ssh
	if params.SshEnable {
		sshCfg = &model.Ssh{
			Host:       params.Ssh.Host,
			Port:       int64(params.Ssh.Port),
			Username:   params.Ssh.Username,
			Kind:       params.Ssh.Kind,
			Password:   params.Ssh.Password,
			PrivateKey: params.Ssh.PrivateKey,
			Passphrase: params.Ssh.Passphrase,
			Timeout:    params.Ssh.Timeout,
		}
	}

	var proxyCfg *model.Proxy
	if params.ProxyEnable {
		proxyCfg = &model.Proxy{
			Protocol: params.Proxy.Protocol,
			Host:     params.Proxy.Host,
			Port:     int64(params.Proxy.Port),
			Username: params.Proxy.Username,
			Password: params.Proxy.Password,
		}
	}

	var tlsCfg *model.Tls
	if params.TlsEnable {
		tlsCfg = &model.Tls{
			Name:       params.Tls.Name,
			UseSni:     bToI(params.Tls.UseSni),
			ServerName: params.Tls.ServerName,
			Verify:     bToI(params.Tls.Verify),
			ClientAuth: bToI(params.Tls.ClientAuth),
			CaCert:     params.Tls.CaCert,
			Cert:       params.Tls.Cert,
			Key:        params.Tls.Key,
		}
	}

	if err := l.svcCtx.RedisManager.Test(&conn, sshCfg, proxyCfg, tlsCfg, 0); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}

func bToI(b bool) int64 {
	if b {
		return 1
	}
	return 0
}
