// Code generated by scorix.
package conn

import (
	"context"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type TestLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewTestLogic(ctx context.Context, svcCtx *svc.ServiceContext) *TestLogic {
	return &TestLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *TestLogic) Test(params *types.ConnectionReq) (*types.Empty, error) {
	conn := model.Connection{
		Mode:             params.Mode,
		Name:             params.Name,
		Network:          params.Network,
		Host:             params.Host,
		Port:             int64(params.Port),
		Addrs:            params.Addrs,
		SentinelMaster:   params.SentinelMaster,
		SentinelUsername: params.SentinelUsername,
		SentinelPassword: params.SentinelPassword,
		Sock:             params.Sock,
		Username:         params.Username,
		Password:         params.Password,
		AddrMapping:      params.AddrMapping,
		ExecTimeout:      params.ExecTimeout,
		DialTimeout:      params.DialTimeout,
		KeySize:          params.KeySize,
		SshEnable:        bToI(params.SshEnable),
		ProxyEnable:      bToI(params.ProxyEnable),
		TlsEnable:        bToI(params.TlsEnable),
	}

	if params.Id != "" && (params.Password == "" || params.SentinelPassword == "") {
		if existing, err := l.svcCtx.ConnectionModel.FindOne(l.ctx, params.Id); err == nil {
			if params.Password == "" {
				conn.Password = existing.Password
			}
			if params.SentinelPassword == "" {
				conn.SentinelPassword = existing.SentinelPassword
			}
		}
	}

	var sshCfg *model.Ssh
	if params.SshEnable && params.SshId != "" {
		s, err := l.svcCtx.SshModel.FindOne(l.ctx, params.SshId)
		if err != nil {
			return nil, err
		}
		sshCfg = s
	}

	var proxyCfg *model.Proxy
	if params.ProxyEnable && params.ProxyId != "" {
		p, err := l.svcCtx.ProxyModel.FindOne(l.ctx, params.ProxyId)
		if err != nil {
			return nil, err
		}
		proxyCfg = p
	}

	var tlsCfg *model.Tls
	if params.TlsEnable && params.TlsId != "" {
		tc, err := l.svcCtx.TlsModel.FindOne(l.ctx, params.TlsId)
		if err != nil {
			return nil, err
		}
		tlsCfg = tc
	}

	if err := l.svcCtx.RedisManager.Test(&conn, sshCfg, proxyCfg, tlsCfg, 0); err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}

func bToI(b bool) int64 {
	if b {
		return 1
	}
	return 0
}
