// Code generated by scorix.
package group

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type ListLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListLogic {
	return &ListLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ListLogic) List(params *types.Empty) (*types.GroupListRes, error) {
	groups, err := l.svcCtx.GroupModel.FindAll(l.ctx)
	if err != nil {
		return nil, err
	}

	var items []types.GroupItem
	for _, g := range groups {
		items = append(items, types.GroupItem{
			Id:        g.ID,
			Name:      g.Name,
			CreatedAt: g.CreatedAt.Unix(),
			UpdatedAt: g.UpdatedAt.Unix(),
		})
	}

	return &types.GroupListRes{
		Items: items,
	}, nil
}
