// Code generated by scorix.
package group

import (
	"context"
	"database/sql"
	"errors"

	"github.com/tradalab/rdms/internal/model"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type UpsertLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpsertLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpsertLogic {
	return &UpsertLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *UpsertLogic) Upsert(params *types.GroupUpsertReq) (*types.UpsertRes, error) {
	if params.Id != "" {
		g, err := l.svcCtx.GroupModel.FindOne(l.ctx, params.Id)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
		if err == nil && g != nil {
			g.Name = params.Name
			if err := l.svcCtx.GroupModel.Update(l.ctx, g); err != nil {
				return nil, err
			}
			return &types.UpsertRes{Id: g.ID}, nil
		}
	}

	g := &model.Group{
		ID:   params.Id,
		Name: params.Name,
	}
	if _, err := l.svcCtx.GroupModel.Insert(l.ctx, g); err != nil {
		return nil, err
	}

	return &types.UpsertRes{Id: g.ID}, nil
}
